export const COMPANION_PLANTING_SLUG = 'biljni-susjedi';
export const COMPANION_PLANTING_PATH = `/${COMPANION_PLANTING_SLUG}`;
export const COMPANION_PLANTING_LAST_REVIEWED = '2026-06-13';

export const QUALITY_HARVEST_SAFETY_SLUG = 'kvaliteta-i-sigurnost-uroda';
export const QUALITY_HARVEST_SAFETY_PATH = `/${QUALITY_HARVEST_SAFETY_SLUG}`;
export const QUALITY_HARVEST_SAFETY_LAST_REVIEWED = '2026-06-03';
