export const environmentAnimalEntityTypeName = 'environmentAnimal';

export const environmentAnimalEntityTypeCategory = {
    name: 'garden-environment',
    label: 'Vrt i okoliš',
    icon: 'leaf',
    order: 'w',
} as const;

export const environmentAnimalEntityType = {
    name: environmentAnimalEntityTypeName,
    label: 'Životinje okoliša',
    icon: 'frog',
    categoryName: environmentAnimalEntityTypeCategory.name,
    order: 'a',
} as const;

// This is the shared wildlife contract already used by other environment
// animals. Butterfly only adds the appearance fields that its stable, seeded
// wing variants need.
export const environmentAnimalAttributeCategories = [
    { name: 'information', label: 'Informacije', order: 'a' },
    { name: 'habitat', label: 'Stanište', order: 'b' },
    { name: 'spawn', label: 'Pojavljivanje', order: 'c' },
    { name: 'behavior', label: 'Ponašanje', order: 'd' },
    { name: 'commerce', label: 'Dostupnost', order: 'e' },
    { name: 'appearance', label: 'Izgled', order: 'f' },
] as const;

export const environmentAnimalAttributeDefinitions = [
    {
        category: 'information',
        name: 'name',
        label: 'Naziv',
        description: 'Stabilni tehnički naziv životinje okoliša.',
        dataType: 'text',
        order: 'aa',
        required: true,
        display: true,
    },
    {
        category: 'information',
        name: 'label',
        label: 'Javni naziv',
        description: 'Hrvatski naziv životinje.',
        dataType: 'text',
        order: 'ab',
        required: true,
        display: true,
    },
    {
        category: 'information',
        name: 'shortDescription',
        label: 'Kratki opis',
        description: 'Sažeti opis uloge životinje u vrtu.',
        dataType: 'text',
        order: 'ac',
        required: true,
        display: true,
    },
    {
        category: 'information',
        name: 'fullDescription',
        label: 'Opis',
        description: 'Detaljan opis prirodnog ponašanja životinje.',
        dataType: 'markdown',
        order: 'ad',
        required: true,
        display: false,
    },
    {
        category: 'habitat',
        name: 'spawnMode',
        label: 'Način pojavljivanja',
        description: 'Izvor jedinke u vrtu.',
        dataType: 'text',
        order: 'ba',
        required: true,
        display: true,
    },
    {
        category: 'habitat',
        name: 'eligibility',
        label: 'Uvjet staništa',
        description: 'Sažetak uvjeta koji dopuštaju pojavljivanje.',
        dataType: 'text',
        order: 'bb',
        required: true,
        display: true,
    },
    {
        category: 'habitat',
        name: 'hosts',
        label: 'Prikladne biljke',
        description: 'Biljke i ukrasi koji privlače životinju.',
        dataType: 'text',
        order: 'bc',
        required: true,
        display: true,
    },
    {
        category: 'habitat',
        name: 'allowedTerrain',
        label: 'Dopušteni tereni',
        description: 'Uvjeti sigurne putanje i mjesta slijetanja.',
        dataType: 'text',
        order: 'bd',
        required: true,
        display: false,
    },
    {
        category: 'habitat',
        name: 'minimumTemperature',
        label: 'Najniža temperatura',
        description: 'Najniža temperatura prikladna za pojavljivanje.',
        dataType: 'number',
        unit: '°C',
        order: 'be',
        required: true,
        display: false,
    },
    {
        category: 'habitat',
        name: 'maximumTemperature',
        label: 'Najviša temperatura',
        description: 'Najviša temperatura prikladna za pojavljivanje.',
        dataType: 'number',
        unit: '°C',
        order: 'bf',
        required: true,
        display: false,
    },
    {
        category: 'habitat',
        name: 'maxWaterDepth',
        label: 'Najveća dubina vode',
        description: 'Najveća dubina vode prikladna za slijetanje.',
        dataType: 'number',
        unit: 'm',
        order: 'bg',
        required: true,
        display: false,
    },
    {
        category: 'habitat',
        name: 'timeOfDay',
        label: 'Dio dana',
        description: 'Dio dana u kojem se životinja pojavljuje.',
        dataType: 'text',
        order: 'bh',
        required: true,
        display: false,
    },
    {
        category: 'habitat',
        name: 'weatherLimits',
        label: 'Vremenski uvjeti',
        description: 'Najveća dopuštena naoblaka i brzina vjetra.',
        dataType: 'text',
        order: 'bi',
        required: true,
        display: false,
    },
    {
        category: 'habitat',
        name: 'persistence',
        label: 'Trajanje pojave',
        description: 'Način čuvanja životinje u vrtu.',
        dataType: 'text',
        order: 'bj',
        required: true,
        display: false,
    },
    {
        category: 'spawn',
        name: 'mode',
        label: 'Način pojavljivanja',
        description: 'Runtime način odabira trenutka i jedinke.',
        dataType: 'text',
        order: 'ca',
        required: true,
        display: true,
    },
    {
        category: 'spawn',
        name: 'maxPopulation',
        label: 'Najveća populacija',
        description: 'Najveći broj jedinki u vrtu.',
        dataType: 'number',
        order: 'cb',
        required: true,
        display: false,
    },
    {
        category: 'spawn',
        name: 'maxPopulationPerHabitat',
        label: 'Najveća populacija po staništu',
        description: 'Najveći broj jedinki uz jednu skupinu cvijeća.',
        dataType: 'number',
        order: 'cc',
        required: true,
        display: false,
    },
    {
        category: 'spawn',
        name: 'cooldownMinSeconds',
        label: 'Najkraća stanka pojavljivanja',
        description: 'Najkraća pauza prije nove jedinke.',
        dataType: 'number',
        unit: 's',
        order: 'cd',
        required: true,
        display: false,
    },
    {
        category: 'spawn',
        name: 'cooldownMaxSeconds',
        label: 'Najduža stanka pojavljivanja',
        description: 'Najduža pauza prije nove jedinke.',
        dataType: 'number',
        unit: 's',
        order: 'ce',
        required: true,
        display: false,
    },
    {
        category: 'spawn',
        name: 'lifetimeMinSeconds',
        label: 'Najkraći posjet',
        description: 'Najkraće trajanje jedne posjete vrtu.',
        dataType: 'number',
        unit: 's',
        order: 'cf',
        required: true,
        display: false,
    },
    {
        category: 'spawn',
        name: 'lifetimeMaxSeconds',
        label: 'Najduži posjet',
        description: 'Najduže trajanje jedne posjete vrtu.',
        dataType: 'number',
        unit: 's',
        order: 'cg',
        required: true,
        display: false,
    },
    {
        category: 'behavior',
        name: 'movement',
        label: 'Kretanje',
        description: 'Sažetak životinjskog kretanja i odmora.',
        dataType: 'markdown',
        order: 'da',
        required: true,
        display: true,
    },
    {
        category: 'behavior',
        name: 'cropImpact',
        label: 'Utjecaj na usjev',
        description: 'Utječe li životinja na stanje biljaka.',
        dataType: 'text',
        order: 'db',
        required: true,
        display: true,
    },
    {
        category: 'behavior',
        name: 'purchasable',
        label: 'Može se kupiti',
        description: 'Kompatibilno polje ponašanja za postojeće zapise.',
        dataType: 'boolean',
        order: 'dc',
        required: true,
        display: true,
    },
    {
        category: 'behavior',
        name: 'animationStates',
        label: 'Animacijska stanja',
        description: 'Stanja koja runtime glatko povezuje.',
        dataType: 'text',
        order: 'dd',
        required: true,
        display: false,
    },
    {
        category: 'behavior',
        name: 'avatarReaction',
        label: 'Reakcija na lika',
        description: 'Način sigurnog izbjegavanja lika u vrtu.',
        dataType: 'text',
        order: 'de',
        required: true,
        display: false,
    },
    {
        category: 'commerce',
        name: 'purchasable',
        label: 'Može se kupiti',
        description: 'Smije li se životinja kupiti ili dobiti u inventar.',
        dataType: 'boolean',
        order: 'ea',
        required: true,
        display: true,
    },
    {
        category: 'commerce',
        name: 'petPickerVisible',
        label: 'Vidljivo u Ljubimcima',
        description: 'Smije li se životinja prikazati u biraču Ljubimci.',
        dataType: 'boolean',
        order: 'eb',
        required: true,
        display: true,
    },
    {
        category: 'appearance',
        name: 'modelName',
        label: '3D model',
        description: 'Naziv registriranog GLB modela.',
        dataType: 'text',
        order: 'fa',
        required: true,
        display: true,
    },
    {
        category: 'appearance',
        name: 'wingVariants',
        label: 'Varijante krila',
        description:
            'JSON popis stabilnih ključeva, hrvatskih naziva, paleta i uzoraka krila.',
        dataType: 'text',
        order: 'fb',
        required: false,
        display: true,
    },
] as const;

export const butterflyWingVariantDirectory = [
    {
        id: 'adriatic-blue',
        label: 'Jadransko plava',
        primary: '#4d8fbd',
        secondary: '#9ccfc5',
        pattern: 'rub i pjege',
    },
    {
        id: 'copper-cream',
        label: 'Bakreno krem',
        primary: '#c66a32',
        secondary: '#edc58f',
        pattern: 'pojas i pjege',
    },
    {
        id: 'plum-gold',
        label: 'Šljiva i zlato',
        primary: '#744b78',
        secondary: '#d7a64a',
        pattern: 'dvostruke pjege',
    },
    {
        id: 'sage-rose',
        label: 'Kadulja i ruža',
        primary: '#799474',
        secondary: '#d8898c',
        pattern: 'rub i pojas',
    },
    {
        id: 'lemon-charcoal',
        label: 'Limun i ugljen',
        primary: '#e9bd3e',
        secondary: '#5d5c57',
        pattern: 'tamni vrhovi',
    },
    {
        id: 'sky-coral',
        label: 'Nebo i koralj',
        primary: '#74add0',
        secondary: '#dd7d68',
        pattern: 'pojas i vanjske pjege',
    },
    {
        id: 'terracotta-mint',
        label: 'Terakota i metvica',
        primary: '#b65d3f',
        secondary: '#87b9a0',
        pattern: 'svijetli rub',
    },
    {
        id: 'violet-ivory',
        label: 'Ljubičica i bjelokost',
        primary: '#765a9a',
        secondary: '#e7d7b7',
        pattern: 'unutarnje i vanjske pjege',
    },
] as const;

export const butterflyEnvironmentAnimal = {
    name: 'Butterfly',
    attributes: {
        'information.name': 'Butterfly',
        'information.label': 'Leptir',
        'information.shortDescription':
            'Nježni oprašivač koji za lijepa dana prirodno posjećuje rascvjetane biljke.',
        'information.fullDescription':
            'Leptiri sami dolaze u vrt kada ima cvijeća, dovoljno dnevnog svjetla i mirnog vremena. Lebde između cvjetova, kratko slijeću i odmaraju sklopljenih krila, a zatim nastavljaju svoj put. Ne kupuju se i ne pojavljuju se u biraču Ljubimci.',
        'habitat.spawnMode': 'environment',
        'habitat.eligibility':
            'Rascvjetane biljke, dnevno svjetlo i mirno vrijeme',
        'habitat.hosts': 'Rascvjetane biljke i cvjetni ukrasi',
        'habitat.allowedTerrain':
            'Sigurna zračna putanja; slijetanje samo na važeći cvjetni cilj iznad prohodnog tla',
        'habitat.minimumTemperature': '12',
        'habitat.maximumTemperature': '35',
        'habitat.maxWaterDepth': '0',
        'habitat.timeOfDay': 'daylight:0.29-0.74',
        'habitat.weatherLimits':
            'cloudCover<=0.52; rain/fog/snow/thunder<=0.06; windSpeed<=1.35',
        'habitat.persistence': 'environment-ephemeral',
        'spawn.mode': 'seeded-environment',
        'spawn.maxPopulation': '6',
        'spawn.maxPopulationPerHabitat': '2',
        'spawn.cooldownMinSeconds': '14',
        'spawn.cooldownMaxSeconds': '14',
        'spawn.lifetimeMinSeconds': '68',
        'spawn.lifetimeMaxSeconds': '112',
        'behavior.movement':
            'Vijugavi let s promjenjivim zamahom krila, naginjanjem, prilaskom cvijetu, slijetanjem, odmorom sklopljenih ili lagano pomičnih krila, polijetanjem i odlaskom iz vrta.',
        'behavior.cropImpact': 'none',
        'behavior.purchasable': 'false',
        'behavior.animationStates':
            'meandering, approaching, landing, resting, taking-off, departing',
        'behavior.avatarReaction':
            'Nježno se udaljava od lika i po potrebi ranije polijeće.',
        'commerce.purchasable': 'false',
        'commerce.petPickerVisible': 'false',
        'appearance.modelName': 'Butterfly',
        'appearance.wingVariants': JSON.stringify(
            butterflyWingVariantDirectory,
        ),
    },
} as const;

export function environmentAnimalAttributePath({
    category,
    name,
}: {
    category: string;
    name: string;
}) {
    return `${category}.${name}`;
}
