import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

// icon.svg is the source artwork for every Delivery app icon.
const appRoot = new URL('../', import.meta.url);
const androidRoot = new URL('../../delivery-android/', import.meta.url);
const source = await readFile(new URL('app/icon.svg', appRoot), 'utf8');
const background = source.match(/<rect[^>]*fill="([^"]+)"/)?.[1];
const mark = source.match(/<path fill="([^"]+)" d="([^"]+)"\s*\/>/);
if (!background || !mark || !source.includes('viewBox="0 0 64 64"')) {
    throw new Error(
        'Expected a 64×64 icon with one background and one filled path.',
    );
}
const [, foreground, path] = mark;
const fullBleed = source.replace(' rx="14"', '');

for (const size of [192, 512]) {
    await sharp(Buffer.from(source))
        .resize(size, size)
        .png()
        .toFile(
            fileURLToPath(
                new URL(`public/web-app-manifest-${size}x${size}.png`, appRoot),
            ),
        );
}
await sharp(Buffer.from(fullBleed))
    .resize(512, 512)
    .removeAlpha()
    .png()
    .toFile(
        fileURLToPath(
            new URL('public/web-app-manifest-maskable-512x512.png', appRoot),
        ),
    );
await sharp(Buffer.from(fullBleed))
    .resize(180, 180)
    .removeAlpha()
    .png()
    .toFile(fileURLToPath(new URL('app/apple-icon.png', appRoot)));

const graphicsRoot = new URL('store/google-play/hr-HR/graphics/', androidRoot);
await writeFile(
    new URL('source/play-icon.svg', graphicsRoot),
    fullBleed.replace('viewBox=', 'width="512" height="512" viewBox='),
);
await sharp(Buffer.from(fullBleed))
    .resize(512, 512)
    .ensureAlpha()
    .png()
    .toFile(fileURLToPath(new URL('play-icon-512x512.png', graphicsRoot)));

function vector({
    size,
    viewport,
    color,
    adaptive = false,
    withBackground = false,
}) {
    const markPath = `<path android:fillColor="${color}" android:pathData="${path}" />`;
    return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by apps/delivery/scripts/generate-icons.mjs. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="${size}dp"
    android:height="${size}dp"
    android:viewportWidth="${viewport}"
    android:viewportHeight="${viewport}">
${withBackground ? `    <path android:fillColor="${background}" android:pathData="M0 0h64v64H0Z" />\n` : ''}${adaptive ? `    <group android:translateX="14" android:translateY="14" android:scaleX="1.25" android:scaleY="1.25">\n        ${markPath}\n    </group>` : `    ${markPath}`}
</vector>
`;
}

const resources = new URL('app/src/main/res/', androidRoot);
for (const name of ['ic_launcher_foreground', 'ic_launcher_monochrome']) {
    await writeFile(
        new URL(`drawable/${name}.xml`, resources),
        vector({ size: 108, viewport: 108, color: foreground, adaptive: true }),
    );
}
await writeFile(
    new URL('drawable/ic_delivery_splash.xml', resources),
    vector({ size: 128, viewport: 64, color: background }),
);
await writeFile(
    new URL('mipmap-anydpi/ic_launcher.xml', resources),
    vector({ size: 48, viewport: 64, color: foreground, withBackground: true }),
);
await writeFile(
    new URL('values/colors.xml', resources),
    `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by apps/delivery/scripts/generate-icons.mjs. -->
<resources>
    <color name="launcher_background">${background}</color>
</resources>
`,
);
