// This file was generated by packages/directory-types/scripts/generateCmsTypeAliases.mjs.
// Do not edit manually. Run `pnpm --filter @gredice/directory-types regenerate:cms-types`.

import type { components } from './v1';

export interface DirectoryEntityDataMap {
    block: components['schemas']['entity-block'];
    brand: components['schemas']['entity-brand'];
    faq: components['schemas']['entity-faq'];
    'faq-category': components['schemas']['entity-faq-category'];
    farmSupply: components['schemas']['entity-farmSupply'];
    hqLocations: components['schemas']['entity-hqLocations'];
    liquidPreparation: components['schemas']['entity-liquidPreparation'];
    occasions: components['schemas']['entity-occasions'];
    operation: components['schemas']['entity-operation'];
    operationFrequency: components['schemas']['entity-operationFrequency'];
    plant: components['schemas']['entity-plant'];
    plantDisease: components['schemas']['entity-plantDisease'];
    plantPest: components['schemas']['entity-plantPest'];
    plantSort: components['schemas']['entity-plantSort'];
    plantStage: components['schemas']['entity-plantStage'];
    seed: components['schemas']['entity-seed'];
}

export type DirectoryEntityTypeName = keyof DirectoryEntityDataMap;
export type DirectoryEntityData<
    TEntityTypeName extends DirectoryEntityTypeName = DirectoryEntityTypeName,
> = DirectoryEntityDataMap[TEntityTypeName];

export type BlockData = DirectoryEntityDataMap['block'];
export type BrandData = DirectoryEntityDataMap['brand'];
export type FaqData = DirectoryEntityDataMap['faq'];
export type FaqCategoryData = DirectoryEntityDataMap['faq-category'];
export type FarmSupplyData = DirectoryEntityDataMap['farmSupply'];
export type HqLocationsData = DirectoryEntityDataMap['hqLocations'];
export type LiquidPreparationData = DirectoryEntityDataMap['liquidPreparation'];
export type OccasionsData = DirectoryEntityDataMap['occasions'];
export type OccasionData = OccasionsData;
export type OperationData = DirectoryEntityDataMap['operation'];
export type OperationFrequencyData =
    DirectoryEntityDataMap['operationFrequency'];
export type PlantData = DirectoryEntityDataMap['plant'];
export type PlantDiseaseData = DirectoryEntityDataMap['plantDisease'];
export type PlantPestData = DirectoryEntityDataMap['plantPest'];
export type PlantSortData = DirectoryEntityDataMap['plantSort'];
export type PlantStageData = DirectoryEntityDataMap['plantStage'];
export type SeedData = DirectoryEntityDataMap['seed'];
