/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /pages
         * @description Get published CMS pages.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["page-summary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pages/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /pages/{slug}
         * @description Get a published CMS page by slug/path.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["page-detail"];
                    };
                };
                /** @description Page not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/plant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /entities/plant
         * @description Get all entities of type plant.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["entity-plant"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/plantSort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /entities/plantSort
         * @description Get all entities of type plantSort.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["entity-plantSort"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/plantStage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /entities/plantStage
         * @description Get all entities of type plantStage.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["entity-plantStage"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /entities/seed
         * @description Get all entities of type seed.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["entity-seed"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/brand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /entities/brand
         * @description Get all entities of type brand.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["entity-brand"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/liquidPreparation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /entities/liquidPreparation
         * @description Get all entities of type liquidPreparation.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["entity-liquidPreparation"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/operation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /entities/operation
         * @description Get all entities of type operation.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["entity-operation"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/operationFrequency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /entities/operationFrequency
         * @description Get all entities of type operationFrequency.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["entity-operationFrequency"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/faq": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /entities/faq
         * @description Get all entities of type faq.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["entity-faq"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/faq-category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /entities/faq-category
         * @description Get all entities of type faq-category.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["entity-faq-category"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/block": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /entities/block
         * @description Get all entities of type block.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["entity-block"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/farmSupply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /entities/farmSupply
         * @description Get all entities of type farmSupply.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["entity-farmSupply"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/occasions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /entities/occasions
         * @description Get all entities of type occasions.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["entity-occasions"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/hqLocations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * /entities/hqLocations
         * @description Get all entities of type hqLocations.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["entity-hqLocations"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        image: {
            /** Format: uri */
            url: string;
        };
        "section-data": {
            component: string;
        } & {
            [key: string]: unknown;
        };
        "page-summary": {
            slug: string;
            title: string;
            /** @enum {string} */
            state: "published";
            /** Format: date-time */
            publishedAt?: string | null;
            metaTitle?: string | null;
            metaDescription?: string | null;
            metaImageUrl?: string | null;
            /** Format: date-time */
            updatedAt: string;
        };
        "page-detail": components["schemas"]["page-summary"] & {
            content: components["schemas"]["section-data"][];
        };
        "entity-plant": {
            id: number;
            entityType: {
                /** @default 1 */
                id: number;
                /** @default plant */
                name: string;
                /** @default Biljka */
                label: string;
            };
            slug: string;
            calendar: {
                /** @description vrijeme sijanja na otvorenom (upisati mjesec pocetka i kraja; npr. 1.5 naznacava sredinu siječnja) */
                sowing?: {
                    start: number;
                    end: number;
                }[];
                /** @description vrijeme presađivanja na otvoreno (upisati mjesec pocetka i kraja; npr. 1.5 naznacava sredinu siječnja) */
                planting?: {
                    start: number;
                    end: number;
                }[];
                /** @description (upisati mjesec pocetka i kraja; npr. 1.5 naznacava sredinu siječnja) */
                harvest: {
                    start: number;
                    end: number;
                }[];
                /** @description vrijeme sijanja u zatvorenom (upisati mjesec pocetka i kraja; npr. 1.5 naznacava sredinu siječnja) */
                propagating?: {
                    start: number;
                    end: number;
                }[];
            };
            information: {
                name: string;
                latinName: string;
                origin: string;
                verified?: boolean;
                description: string;
                soilPreparation: string;
                sowing?: string;
                planting?: string;
                growth: string;
                maintenance: string;
                watering: string;
                flowering?: string;
                /** @description Informacije o berbi biljke. */
                harvest: string;
                storage: string;
                tip?: {
                    header: string;
                    /** @description Markdown formatted text */
                    content: string;
                }[];
                /** @description (popis dozvoljenih operacija za biljku) */
                operations: {
                    id: number;
                    attributes: {
                        /** @description (jedno od: optional, once, periodic, daily, weekly, biweekly, monthly) */
                        frequency?: string;
                        /** @description (na koji stadij biljke se primjenjuje radnja) */
                        stage: {
                            id: number;
                            information: {
                                name: string;
                                label: string;
                            };
                        };
                        /** @description (na što se primjenjuje operacije - jedno od: farm, garden, raisedBedFull, raisedBed1m, plant) */
                        application: string;
                        /** @description (broj dana kada se radi operacija relativno na životni ciklus biljke) */
                        relativeDays?: number;
                        /** @description (ako je radnja za dostavu, korisnik mora ugovoriti dostavu za odrađivanje ove radnje npr. Branje svih plodova) */
                        deliverable: boolean;
                        /** @description (vrijeme potrebno za izvršavanje radnje u minutama) */
                        duration: number;
                        /** @description (interna radnja se ne dojavljuje niti prikazuje korisnicima aplikacije - namjenjena je za poslove farmera) */
                        internal?: boolean;
                        printLabel?: boolean;
                        /** @description Jedan ili više točnih tekućih pripravaka koji se mogu koristiti za ovu radnju. Koristi se kod radnji primjene/tretmana kada radnja može trošiti pripravke različitih brendova ili pakiranja. Primjer: liquidPreparation#566 za pripravak za otpornost rajčice 750 ml; kasnije se može dodati i drugi pripravak iste namjene u drugom pakiranju. */
                        liquidPreparation?: {
                            id: number;
                            images?: {
                                cover?: components["schemas"]["image"];
                            };
                            information: {
                                brandName: string;
                                barcode?: string;
                                name: string;
                                label: string;
                                productUrl?: string;
                            };
                            attributes: {
                                volumeMl: number;
                                price?: number;
                                certification?: string;
                                form?: string;
                            };
                            application: {
                                dosage: string;
                                purpose: string;
                                target: string;
                                applicationMethod: string;
                                frequencyRecommendation?: string;
                            };
                        }[];
                        /** @description Tehnički naziv tipa entiteta čija se zaliha provjerava ili koristi kroz ovu radnju. Ovo polje služi za usmjeravanje prema pravoj evidenciji zalihe. Primjeri: farmSupply, seed, liquidPreparation. */
                        inventoryEntityType?: string;
                        /** @description Grupa zalihe unutar odabranog tipa entiteta. Koristi se za inventurne radnje koje broje širu skupinu zalihe, a ne samo jedan proizvod. Primjeri: raisedBedBoards, seed, plantProtection, paperDeliveryBag. */
                        inventoryKind?: string;
                        /** @description Jedan ili više konkretnih materijala iz tipa farmSupply koji pripadaju ovoj inventurnoj radnji. Koristi se kada jedna radnja pokriva više dobavljača, brendova, dimenzija ili pakiranja istog materijala. Primjer: farmSupply#573 za daske za gredice; kasnije se mogu dodati posebne daske drugog dobavljača ili druge dimenzije. */
                        inventorySupply?: {
                            id: number;
                            images?: {
                                cover?: components["schemas"]["image"];
                            };
                            attributes: {
                                category: string;
                                kind: string;
                                packSize?: number;
                                unit: string;
                                notes?: string;
                                /** @description (cijena pakiranja u EUR) */
                                price: number;
                            };
                            information: {
                                barcode?: string;
                                name: string;
                                label: string;
                                description?: string;
                                supplier?: string;
                                productUrl?: string;
                            };
                        }[];
                    };
                    information: {
                        /** @description (puni opis operacije) */
                        description: string;
                        /** @description (kratki opis operacije) */
                        shortDescription: string;
                        /** @description (tehnički naziv operacije - jednom postavljen ne smije se mjenjati!) */
                        name: string;
                        /** @description (prevedeni naziv operacije) */
                        label: string;
                        /** @description (postupak za izvršavanje radnje) */
                        instructions: string;
                    };
                    prices: {
                        /** @description (EUR cijena za jednu operaciju) */
                        perOperation: number;
                        /** @description (EUR cijena s popustom) */
                        discounted?: number;
                        /** @description (opis popusta npr. "Za kupnju 18 biljaka") */
                        discountDescription?: string;
                    };
                    image?: {
                        cover?: components["schemas"]["image"];
                    };
                    conditions: {
                        /** @description (da li se mogu proložiti slike za završetak radnje) */
                        completionAttachImages: boolean;
                        /** @description (da li je obavezno proložiti slike za završetak radnje) */
                        completionAttachImagesRequired: boolean;
                        /** @description (da li se mo\e priložiti napomena za završetak radnje) */
                        completionAttachNotes: boolean;
                        /** @description (da li je obavezno proložiti napomenu za završetak radnje) */
                        completionAttachNotesRequired: boolean;
                    };
                    actions?: {
                        removePlant?: boolean;
                    };
                }[];
            };
            attributes: {
                /** @description (u gramima) */
                yieldMin: number;
                /** @description (u gramima) */
                yieldMax: number;
                /** @description (u danima) */
                harvestWindowMin: number;
                /** @description (u danima) */
                harvestWindowMax: number;
                /** @description (Lagano (pješčano), Srednje (ilovasto), Teško (glineno)) */
                soil: string;
                /** @description (od 0 do 1 gdje 0 označava potpuni hlad a 1 direktno sunce) */
                light: number;
                /** @description (u centimetrima) */
                seedingDepth: number;
                /** @description (Niske potrebe, Srednje potrebe, Visoke potrebe) */
                nutrients: string;
                /** @description (Suho tlo, Vlažno tlo, Mokro tlo) */
                water: string;
                /** @description (u centimetrima) */
                seedingDistance: number;
                /** @description (Klijanje pod svijetlosti, Klijanje u mraku) */
                germinationType: string;
                /** @description (u stupnjevima °C) */
                gernimationTemperature: number;
                germinationWindowMin: number;
                /** @description (u danima) */
                germinationWindowMax: number;
                /** @description (u danima) */
                growthWindowMin: number;
                /** @description (u danima) */
                growthWindowMax: number;
                /** @description ('perPlant' ako je mjera po biljci ili 'perField' ako je mjera za jedno polje gredice) */
                yieldType: string;
                /** @description (da li je polje čisto nakon branja biljke; u suprotnom je pokrebna radnja uklanjanja biljke) */
                cleanHarvest: boolean;
            };
            image: {
                cover: components["schemas"]["image"];
            };
            prices: {
                /** @description (EUR cijena za jednu biljku - presadnica ili 30x30cm sijanje) */
                perPlant: number;
            };
            store: {
                availableInStore: boolean;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        "entity-plantSort": {
            id: number;
            entityType: {
                /** @default 11 */
                id: number;
                /** @default plantSort */
                name: string;
                /** @default Sorta biljke */
                label: string;
            };
            slug: string;
            information: {
                plant: {
                    id: number;
                    calendar: {
                        /** @description vrijeme sijanja na otvorenom (upisati mjesec pocetka i kraja; npr. 1.5 naznacava sredinu siječnja) */
                        sowing?: {
                            start: number;
                            end: number;
                        }[];
                        /** @description vrijeme presađivanja na otvoreno (upisati mjesec pocetka i kraja; npr. 1.5 naznacava sredinu siječnja) */
                        planting?: {
                            start: number;
                            end: number;
                        }[];
                        /** @description (upisati mjesec pocetka i kraja; npr. 1.5 naznacava sredinu siječnja) */
                        harvest: {
                            start: number;
                            end: number;
                        }[];
                        /** @description vrijeme sijanja u zatvorenom (upisati mjesec pocetka i kraja; npr. 1.5 naznacava sredinu siječnja) */
                        propagating?: {
                            start: number;
                            end: number;
                        }[];
                    };
                    information: {
                        name: string;
                        latinName: string;
                        origin: string;
                        verified?: boolean;
                        description: string;
                        soilPreparation: string;
                        sowing?: string;
                        planting?: string;
                        growth: string;
                        maintenance: string;
                        watering: string;
                        flowering?: string;
                        /** @description Informacije o berbi biljke. */
                        harvest: string;
                        storage: string;
                        tip?: {
                            header: string;
                            /** @description Markdown formatted text */
                            content: string;
                        }[];
                        /** @description (popis dozvoljenih operacija za biljku) */
                        operations: {
                            id: number;
                            attributes: {
                                /** @description (jedno od: optional, once, periodic, daily, weekly, biweekly, monthly) */
                                frequency?: string;
                                /** @description (na koji stadij biljke se primjenjuje radnja) */
                                stage: {
                                    id: number;
                                    information: {
                                        name: string;
                                        label: string;
                                    };
                                };
                                /** @description (na što se primjenjuje operacije - jedno od: farm, garden, raisedBedFull, raisedBed1m, plant) */
                                application: string;
                                /** @description (broj dana kada se radi operacija relativno na životni ciklus biljke) */
                                relativeDays?: number;
                                /** @description (ako je radnja za dostavu, korisnik mora ugovoriti dostavu za odrađivanje ove radnje npr. Branje svih plodova) */
                                deliverable: boolean;
                                /** @description (vrijeme potrebno za izvršavanje radnje u minutama) */
                                duration: number;
                                /** @description (interna radnja se ne dojavljuje niti prikazuje korisnicima aplikacije - namjenjena je za poslove farmera) */
                                internal?: boolean;
                                printLabel?: boolean;
                                /** @description Jedan ili više točnih tekućih pripravaka koji se mogu koristiti za ovu radnju. Koristi se kod radnji primjene/tretmana kada radnja može trošiti pripravke različitih brendova ili pakiranja. Primjer: liquidPreparation#566 za pripravak za otpornost rajčice 750 ml; kasnije se može dodati i drugi pripravak iste namjene u drugom pakiranju. */
                                liquidPreparation?: {
                                    id: number;
                                    images?: {
                                        cover?: components["schemas"]["image"];
                                    };
                                    information: {
                                        brandName: string;
                                        barcode?: string;
                                        name: string;
                                        label: string;
                                        productUrl?: string;
                                    };
                                    attributes: {
                                        volumeMl: number;
                                        price?: number;
                                        certification?: string;
                                        form?: string;
                                    };
                                    application: {
                                        dosage: string;
                                        purpose: string;
                                        target: string;
                                        applicationMethod: string;
                                        frequencyRecommendation?: string;
                                    };
                                }[];
                                /** @description Tehnički naziv tipa entiteta čija se zaliha provjerava ili koristi kroz ovu radnju. Ovo polje služi za usmjeravanje prema pravoj evidenciji zalihe. Primjeri: farmSupply, seed, liquidPreparation. */
                                inventoryEntityType?: string;
                                /** @description Grupa zalihe unutar odabranog tipa entiteta. Koristi se za inventurne radnje koje broje širu skupinu zalihe, a ne samo jedan proizvod. Primjeri: raisedBedBoards, seed, plantProtection, paperDeliveryBag. */
                                inventoryKind?: string;
                                /** @description Jedan ili više konkretnih materijala iz tipa farmSupply koji pripadaju ovoj inventurnoj radnji. Koristi se kada jedna radnja pokriva više dobavljača, brendova, dimenzija ili pakiranja istog materijala. Primjer: farmSupply#573 za daske za gredice; kasnije se mogu dodati posebne daske drugog dobavljača ili druge dimenzije. */
                                inventorySupply?: {
                                    id: number;
                                    images?: {
                                        cover?: components["schemas"]["image"];
                                    };
                                    attributes: {
                                        category: string;
                                        kind: string;
                                        packSize?: number;
                                        unit: string;
                                        notes?: string;
                                        /** @description (cijena pakiranja u EUR) */
                                        price: number;
                                    };
                                    information: {
                                        barcode?: string;
                                        name: string;
                                        label: string;
                                        description?: string;
                                        supplier?: string;
                                        productUrl?: string;
                                    };
                                }[];
                            };
                            information: {
                                /** @description (puni opis operacije) */
                                description: string;
                                /** @description (kratki opis operacije) */
                                shortDescription: string;
                                /** @description (tehnički naziv operacije - jednom postavljen ne smije se mjenjati!) */
                                name: string;
                                /** @description (prevedeni naziv operacije) */
                                label: string;
                                /** @description (postupak za izvršavanje radnje) */
                                instructions: string;
                            };
                            prices: {
                                /** @description (EUR cijena za jednu operaciju) */
                                perOperation: number;
                                /** @description (EUR cijena s popustom) */
                                discounted?: number;
                                /** @description (opis popusta npr. "Za kupnju 18 biljaka") */
                                discountDescription?: string;
                            };
                            image?: {
                                cover?: components["schemas"]["image"];
                            };
                            conditions: {
                                /** @description (da li se mogu proložiti slike za završetak radnje) */
                                completionAttachImages: boolean;
                                /** @description (da li je obavezno proložiti slike za završetak radnje) */
                                completionAttachImagesRequired: boolean;
                                /** @description (da li se mo\e priložiti napomena za završetak radnje) */
                                completionAttachNotes: boolean;
                                /** @description (da li je obavezno proložiti napomenu za završetak radnje) */
                                completionAttachNotesRequired: boolean;
                            };
                            actions?: {
                                removePlant?: boolean;
                            };
                        }[];
                    };
                    attributes: {
                        /** @description (u gramima) */
                        yieldMin: number;
                        /** @description (u gramima) */
                        yieldMax: number;
                        /** @description (u danima) */
                        harvestWindowMin: number;
                        /** @description (u danima) */
                        harvestWindowMax: number;
                        /** @description (Lagano (pješčano), Srednje (ilovasto), Teško (glineno)) */
                        soil: string;
                        /** @description (od 0 do 1 gdje 0 označava potpuni hlad a 1 direktno sunce) */
                        light: number;
                        /** @description (u centimetrima) */
                        seedingDepth: number;
                        /** @description (Niske potrebe, Srednje potrebe, Visoke potrebe) */
                        nutrients: string;
                        /** @description (Suho tlo, Vlažno tlo, Mokro tlo) */
                        water: string;
                        /** @description (u centimetrima) */
                        seedingDistance: number;
                        /** @description (Klijanje pod svijetlosti, Klijanje u mraku) */
                        germinationType: string;
                        /** @description (u stupnjevima °C) */
                        gernimationTemperature: number;
                        germinationWindowMin: number;
                        /** @description (u danima) */
                        germinationWindowMax: number;
                        /** @description (u danima) */
                        growthWindowMin: number;
                        /** @description (u danima) */
                        growthWindowMax: number;
                        /** @description ('perPlant' ako je mjera po biljci ili 'perField' ako je mjera za jedno polje gredice) */
                        yieldType: string;
                        /** @description (da li je polje čisto nakon branja biljke; u suprotnom je pokrebna radnja uklanjanja biljke) */
                        cleanHarvest: boolean;
                    };
                    image: {
                        cover: components["schemas"]["image"];
                    };
                    prices: {
                        /** @description (EUR cijena za jednu biljku - presadnica ili 30x30cm sijanje) */
                        perPlant: number;
                    };
                    store: {
                        availableInStore: boolean;
                    };
                };
                name: string;
                description?: string;
                shortDescription: string;
                latinName?: string;
                sowing?: string;
                origin?: string;
                watering?: string;
                soilPreparation?: string;
                growth?: string;
                storage?: string;
                maintenance?: string;
                harvest?: string;
                planting?: string;
                flowering?: string;
            };
            image: {
                cover: components["schemas"]["image"];
            };
            store: {
                availableInStore: boolean;
            };
            attributes: {
                /** @description (vrsta reprodukcije sorte dostupne u Gredicama; "seed" ili "bulb") */
                reproductionType: string;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        "entity-plantStage": {
            id: number;
            entityType: {
                /** @default 12 */
                id: number;
                /** @default plantStage */
                name: string;
                /** @default Stadij biljke */
                label: string;
            };
            slug: string;
            information: {
                name: string;
                label: string;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        "entity-seed": {
            id: number;
            entityType: {
                /** @default 15 */
                id: number;
                /** @default seed */
                name: string;
                /** @default Sjeme */
                label: string;
            };
            slug: string;
            images?: {
                cover?: components["schemas"]["image"];
                /** @description (slika pozadine pakiranja) */
                back?: components["schemas"]["image"];
            };
            information: {
                brand: {
                    id: number;
                    information: {
                        name: string;
                        website?: string;
                    };
                };
                barcode: string;
                name: string;
                plant: {
                    id: number;
                    calendar: {
                        /** @description vrijeme sijanja na otvorenom (upisati mjesec pocetka i kraja; npr. 1.5 naznacava sredinu siječnja) */
                        sowing?: {
                            start: number;
                            end: number;
                        }[];
                        /** @description vrijeme presađivanja na otvoreno (upisati mjesec pocetka i kraja; npr. 1.5 naznacava sredinu siječnja) */
                        planting?: {
                            start: number;
                            end: number;
                        }[];
                        /** @description (upisati mjesec pocetka i kraja; npr. 1.5 naznacava sredinu siječnja) */
                        harvest: {
                            start: number;
                            end: number;
                        }[];
                        /** @description vrijeme sijanja u zatvorenom (upisati mjesec pocetka i kraja; npr. 1.5 naznacava sredinu siječnja) */
                        propagating?: {
                            start: number;
                            end: number;
                        }[];
                    };
                    information: {
                        name: string;
                        latinName: string;
                        origin: string;
                        verified?: boolean;
                        description: string;
                        soilPreparation: string;
                        sowing?: string;
                        planting?: string;
                        growth: string;
                        maintenance: string;
                        watering: string;
                        flowering?: string;
                        /** @description Informacije o berbi biljke. */
                        harvest: string;
                        storage: string;
                        tip?: {
                            header: string;
                            /** @description Markdown formatted text */
                            content: string;
                        }[];
                        /** @description (popis dozvoljenih operacija za biljku) */
                        operations: {
                            id: number;
                            attributes: {
                                /** @description (jedno od: optional, once, periodic, daily, weekly, biweekly, monthly) */
                                frequency?: string;
                                /** @description (na koji stadij biljke se primjenjuje radnja) */
                                stage: {
                                    id: number;
                                    information: {
                                        name: string;
                                        label: string;
                                    };
                                };
                                /** @description (na što se primjenjuje operacije - jedno od: farm, garden, raisedBedFull, raisedBed1m, plant) */
                                application: string;
                                /** @description (broj dana kada se radi operacija relativno na životni ciklus biljke) */
                                relativeDays?: number;
                                /** @description (ako je radnja za dostavu, korisnik mora ugovoriti dostavu za odrađivanje ove radnje npr. Branje svih plodova) */
                                deliverable: boolean;
                                /** @description (vrijeme potrebno za izvršavanje radnje u minutama) */
                                duration: number;
                                /** @description (interna radnja se ne dojavljuje niti prikazuje korisnicima aplikacije - namjenjena je za poslove farmera) */
                                internal?: boolean;
                                printLabel?: boolean;
                                /** @description Jedan ili više točnih tekućih pripravaka koji se mogu koristiti za ovu radnju. Koristi se kod radnji primjene/tretmana kada radnja može trošiti pripravke različitih brendova ili pakiranja. Primjer: liquidPreparation#566 za pripravak za otpornost rajčice 750 ml; kasnije se može dodati i drugi pripravak iste namjene u drugom pakiranju. */
                                liquidPreparation?: {
                                    id: number;
                                    images?: {
                                        cover?: components["schemas"]["image"];
                                    };
                                    information: {
                                        brandName: string;
                                        barcode?: string;
                                        name: string;
                                        label: string;
                                        productUrl?: string;
                                    };
                                    attributes: {
                                        volumeMl: number;
                                        price?: number;
                                        certification?: string;
                                        form?: string;
                                    };
                                    application: {
                                        dosage: string;
                                        purpose: string;
                                        target: string;
                                        applicationMethod: string;
                                        frequencyRecommendation?: string;
                                    };
                                }[];
                                /** @description Tehnički naziv tipa entiteta čija se zaliha provjerava ili koristi kroz ovu radnju. Ovo polje služi za usmjeravanje prema pravoj evidenciji zalihe. Primjeri: farmSupply, seed, liquidPreparation. */
                                inventoryEntityType?: string;
                                /** @description Grupa zalihe unutar odabranog tipa entiteta. Koristi se za inventurne radnje koje broje širu skupinu zalihe, a ne samo jedan proizvod. Primjeri: raisedBedBoards, seed, plantProtection, paperDeliveryBag. */
                                inventoryKind?: string;
                                /** @description Jedan ili više konkretnih materijala iz tipa farmSupply koji pripadaju ovoj inventurnoj radnji. Koristi se kada jedna radnja pokriva više dobavljača, brendova, dimenzija ili pakiranja istog materijala. Primjer: farmSupply#573 za daske za gredice; kasnije se mogu dodati posebne daske drugog dobavljača ili druge dimenzije. */
                                inventorySupply?: {
                                    id: number;
                                    images?: {
                                        cover?: components["schemas"]["image"];
                                    };
                                    attributes: {
                                        category: string;
                                        kind: string;
                                        packSize?: number;
                                        unit: string;
                                        notes?: string;
                                        /** @description (cijena pakiranja u EUR) */
                                        price: number;
                                    };
                                    information: {
                                        barcode?: string;
                                        name: string;
                                        label: string;
                                        description?: string;
                                        supplier?: string;
                                        productUrl?: string;
                                    };
                                }[];
                            };
                            information: {
                                /** @description (puni opis operacije) */
                                description: string;
                                /** @description (kratki opis operacije) */
                                shortDescription: string;
                                /** @description (tehnički naziv operacije - jednom postavljen ne smije se mjenjati!) */
                                name: string;
                                /** @description (prevedeni naziv operacije) */
                                label: string;
                                /** @description (postupak za izvršavanje radnje) */
                                instructions: string;
                            };
                            prices: {
                                /** @description (EUR cijena za jednu operaciju) */
                                perOperation: number;
                                /** @description (EUR cijena s popustom) */
                                discounted?: number;
                                /** @description (opis popusta npr. "Za kupnju 18 biljaka") */
                                discountDescription?: string;
                            };
                            image?: {
                                cover?: components["schemas"]["image"];
                            };
                            conditions: {
                                /** @description (da li se mogu proložiti slike za završetak radnje) */
                                completionAttachImages: boolean;
                                /** @description (da li je obavezno proložiti slike za završetak radnje) */
                                completionAttachImagesRequired: boolean;
                                /** @description (da li se mo\e priložiti napomena za završetak radnje) */
                                completionAttachNotes: boolean;
                                /** @description (da li je obavezno proložiti napomenu za završetak radnje) */
                                completionAttachNotesRequired: boolean;
                            };
                            actions?: {
                                removePlant?: boolean;
                            };
                        }[];
                    };
                    attributes: {
                        /** @description (u gramima) */
                        yieldMin: number;
                        /** @description (u gramima) */
                        yieldMax: number;
                        /** @description (u danima) */
                        harvestWindowMin: number;
                        /** @description (u danima) */
                        harvestWindowMax: number;
                        /** @description (Lagano (pješčano), Srednje (ilovasto), Teško (glineno)) */
                        soil: string;
                        /** @description (od 0 do 1 gdje 0 označava potpuni hlad a 1 direktno sunce) */
                        light: number;
                        /** @description (u centimetrima) */
                        seedingDepth: number;
                        /** @description (Niske potrebe, Srednje potrebe, Visoke potrebe) */
                        nutrients: string;
                        /** @description (Suho tlo, Vlažno tlo, Mokro tlo) */
                        water: string;
                        /** @description (u centimetrima) */
                        seedingDistance: number;
                        /** @description (Klijanje pod svijetlosti, Klijanje u mraku) */
                        germinationType: string;
                        /** @description (u stupnjevima °C) */
                        gernimationTemperature: number;
                        germinationWindowMin: number;
                        /** @description (u danima) */
                        germinationWindowMax: number;
                        /** @description (u danima) */
                        growthWindowMin: number;
                        /** @description (u danima) */
                        growthWindowMax: number;
                        /** @description ('perPlant' ako je mjera po biljci ili 'perField' ako je mjera za jedno polje gredice) */
                        yieldType: string;
                        /** @description (da li je polje čisto nakon branja biljke; u suprotnom je pokrebna radnja uklanjanja biljke) */
                        cleanHarvest: boolean;
                    };
                    image: {
                        cover: components["schemas"]["image"];
                    };
                    prices: {
                        /** @description (EUR cijena za jednu biljku - presadnica ili 30x30cm sijanje) */
                        perPlant: number;
                    };
                    store: {
                        availableInStore: boolean;
                    };
                };
                plantSort: {
                    id: number;
                    information: {
                        plant: {
                            id: number;
                            calendar: {
                                /** @description vrijeme sijanja na otvorenom (upisati mjesec pocetka i kraja; npr. 1.5 naznacava sredinu siječnja) */
                                sowing?: {
                                    start: number;
                                    end: number;
                                }[];
                                /** @description vrijeme presađivanja na otvoreno (upisati mjesec pocetka i kraja; npr. 1.5 naznacava sredinu siječnja) */
                                planting?: {
                                    start: number;
                                    end: number;
                                }[];
                                /** @description (upisati mjesec pocetka i kraja; npr. 1.5 naznacava sredinu siječnja) */
                                harvest: {
                                    start: number;
                                    end: number;
                                }[];
                                /** @description vrijeme sijanja u zatvorenom (upisati mjesec pocetka i kraja; npr. 1.5 naznacava sredinu siječnja) */
                                propagating?: {
                                    start: number;
                                    end: number;
                                }[];
                            };
                            information: {
                                name: string;
                                latinName: string;
                                origin: string;
                                verified?: boolean;
                                description: string;
                                soilPreparation: string;
                                sowing?: string;
                                planting?: string;
                                growth: string;
                                maintenance: string;
                                watering: string;
                                flowering?: string;
                                /** @description Informacije o berbi biljke. */
                                harvest: string;
                                storage: string;
                                tip?: {
                                    header: string;
                                    /** @description Markdown formatted text */
                                    content: string;
                                }[];
                                /** @description (popis dozvoljenih operacija za biljku) */
                                operations: {
                                    id: number;
                                    attributes: {
                                        /** @description (jedno od: optional, once, periodic, daily, weekly, biweekly, monthly) */
                                        frequency?: string;
                                        /** @description (na koji stadij biljke se primjenjuje radnja) */
                                        stage: {
                                            id: number;
                                            information: {
                                                name: string;
                                                label: string;
                                            };
                                        };
                                        /** @description (na što se primjenjuje operacije - jedno od: farm, garden, raisedBedFull, raisedBed1m, plant) */
                                        application: string;
                                        /** @description (broj dana kada se radi operacija relativno na životni ciklus biljke) */
                                        relativeDays?: number;
                                        /** @description (ako je radnja za dostavu, korisnik mora ugovoriti dostavu za odrađivanje ove radnje npr. Branje svih plodova) */
                                        deliverable: boolean;
                                        /** @description (vrijeme potrebno za izvršavanje radnje u minutama) */
                                        duration: number;
                                        /** @description (interna radnja se ne dojavljuje niti prikazuje korisnicima aplikacije - namjenjena je za poslove farmera) */
                                        internal?: boolean;
                                        printLabel?: boolean;
                                        /** @description Jedan ili više točnih tekućih pripravaka koji se mogu koristiti za ovu radnju. Koristi se kod radnji primjene/tretmana kada radnja može trošiti pripravke različitih brendova ili pakiranja. Primjer: liquidPreparation#566 za pripravak za otpornost rajčice 750 ml; kasnije se može dodati i drugi pripravak iste namjene u drugom pakiranju. */
                                        liquidPreparation?: {
                                            id: number;
                                            images?: {
                                                cover?: components["schemas"]["image"];
                                            };
                                            information: {
                                                brandName: string;
                                                barcode?: string;
                                                name: string;
                                                label: string;
                                                productUrl?: string;
                                            };
                                            attributes: {
                                                volumeMl: number;
                                                price?: number;
                                                certification?: string;
                                                form?: string;
                                            };
                                            application: {
                                                dosage: string;
                                                purpose: string;
                                                target: string;
                                                applicationMethod: string;
                                                frequencyRecommendation?: string;
                                            };
                                        }[];
                                        /** @description Tehnički naziv tipa entiteta čija se zaliha provjerava ili koristi kroz ovu radnju. Ovo polje služi za usmjeravanje prema pravoj evidenciji zalihe. Primjeri: farmSupply, seed, liquidPreparation. */
                                        inventoryEntityType?: string;
                                        /** @description Grupa zalihe unutar odabranog tipa entiteta. Koristi se za inventurne radnje koje broje širu skupinu zalihe, a ne samo jedan proizvod. Primjeri: raisedBedBoards, seed, plantProtection, paperDeliveryBag. */
                                        inventoryKind?: string;
                                        /** @description Jedan ili više konkretnih materijala iz tipa farmSupply koji pripadaju ovoj inventurnoj radnji. Koristi se kada jedna radnja pokriva više dobavljača, brendova, dimenzija ili pakiranja istog materijala. Primjer: farmSupply#573 za daske za gredice; kasnije se mogu dodati posebne daske drugog dobavljača ili druge dimenzije. */
                                        inventorySupply?: {
                                            id: number;
                                            images?: {
                                                cover?: components["schemas"]["image"];
                                            };
                                            attributes: {
                                                category: string;
                                                kind: string;
                                                packSize?: number;
                                                unit: string;
                                                notes?: string;
                                                /** @description (cijena pakiranja u EUR) */
                                                price: number;
                                            };
                                            information: {
                                                barcode?: string;
                                                name: string;
                                                label: string;
                                                description?: string;
                                                supplier?: string;
                                                productUrl?: string;
                                            };
                                        }[];
                                    };
                                    information: {
                                        /** @description (puni opis operacije) */
                                        description: string;
                                        /** @description (kratki opis operacije) */
                                        shortDescription: string;
                                        /** @description (tehnički naziv operacije - jednom postavljen ne smije se mjenjati!) */
                                        name: string;
                                        /** @description (prevedeni naziv operacije) */
                                        label: string;
                                        /** @description (postupak za izvršavanje radnje) */
                                        instructions: string;
                                    };
                                    prices: {
                                        /** @description (EUR cijena za jednu operaciju) */
                                        perOperation: number;
                                        /** @description (EUR cijena s popustom) */
                                        discounted?: number;
                                        /** @description (opis popusta npr. "Za kupnju 18 biljaka") */
                                        discountDescription?: string;
                                    };
                                    image?: {
                                        cover?: components["schemas"]["image"];
                                    };
                                    conditions: {
                                        /** @description (da li se mogu proložiti slike za završetak radnje) */
                                        completionAttachImages: boolean;
                                        /** @description (da li je obavezno proložiti slike za završetak radnje) */
                                        completionAttachImagesRequired: boolean;
                                        /** @description (da li se mo\e priložiti napomena za završetak radnje) */
                                        completionAttachNotes: boolean;
                                        /** @description (da li je obavezno proložiti napomenu za završetak radnje) */
                                        completionAttachNotesRequired: boolean;
                                    };
                                    actions?: {
                                        removePlant?: boolean;
                                    };
                                }[];
                            };
                            attributes: {
                                /** @description (u gramima) */
                                yieldMin: number;
                                /** @description (u gramima) */
                                yieldMax: number;
                                /** @description (u danima) */
                                harvestWindowMin: number;
                                /** @description (u danima) */
                                harvestWindowMax: number;
                                /** @description (Lagano (pješčano), Srednje (ilovasto), Teško (glineno)) */
                                soil: string;
                                /** @description (od 0 do 1 gdje 0 označava potpuni hlad a 1 direktno sunce) */
                                light: number;
                                /** @description (u centimetrima) */
                                seedingDepth: number;
                                /** @description (Niske potrebe, Srednje potrebe, Visoke potrebe) */
                                nutrients: string;
                                /** @description (Suho tlo, Vlažno tlo, Mokro tlo) */
                                water: string;
                                /** @description (u centimetrima) */
                                seedingDistance: number;
                                /** @description (Klijanje pod svijetlosti, Klijanje u mraku) */
                                germinationType: string;
                                /** @description (u stupnjevima °C) */
                                gernimationTemperature: number;
                                germinationWindowMin: number;
                                /** @description (u danima) */
                                germinationWindowMax: number;
                                /** @description (u danima) */
                                growthWindowMin: number;
                                /** @description (u danima) */
                                growthWindowMax: number;
                                /** @description ('perPlant' ako je mjera po biljci ili 'perField' ako je mjera za jedno polje gredice) */
                                yieldType: string;
                                /** @description (da li je polje čisto nakon branja biljke; u suprotnom je pokrebna radnja uklanjanja biljke) */
                                cleanHarvest: boolean;
                            };
                            image: {
                                cover: components["schemas"]["image"];
                            };
                            prices: {
                                /** @description (EUR cijena za jednu biljku - presadnica ili 30x30cm sijanje) */
                                perPlant: number;
                            };
                            store: {
                                availableInStore: boolean;
                            };
                        };
                        name: string;
                        description?: string;
                        shortDescription: string;
                        latinName?: string;
                        sowing?: string;
                        origin?: string;
                        watering?: string;
                        soilPreparation?: string;
                        growth?: string;
                        storage?: string;
                        maintenance?: string;
                        harvest?: string;
                        planting?: string;
                        flowering?: string;
                    };
                    image: {
                        cover: components["schemas"]["image"];
                    };
                    store: {
                        availableInStore: boolean;
                    };
                    attributes: {
                        /** @description (vrsta reprodukcije sorte dostupne u Gredicama; "seed" ili "bulb") */
                        reproductionType: string;
                    };
                };
                countryOfOrigin?: string;
            };
            attributes: {
                /** @description (cijena pakiranja u EUR) */
                price: number;
                /** @description (težina pakiranja u gramima) */
                weight: number;
                germinationPercentage?: number;
            };
            application?: {
                /** @description (površina primjene pakiranja u m2) */
                applicationArea?: number;
                /** @description (broj biljaka u pakiranju) */
                applicationPlants?: number;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        "entity-brand": {
            id: number;
            entityType: {
                /** @default 16 */
                id: number;
                /** @default brand */
                name: string;
                /** @default Brend sjemena */
                label: string;
            };
            slug: string;
            information: {
                name: string;
                website?: string;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        "entity-liquidPreparation": {
            id: number;
            entityType: {
                /** @default 19 */
                id: number;
                /** @default liquidPreparation */
                name: string;
                /** @default Tekući pripravci */
                label: string;
            };
            slug: string;
            images?: {
                cover?: components["schemas"]["image"];
            };
            information: {
                brandName: string;
                barcode?: string;
                name: string;
                label: string;
                productUrl?: string;
            };
            attributes: {
                volumeMl: number;
                price?: number;
                certification?: string;
                form?: string;
            };
            application: {
                dosage: string;
                purpose: string;
                target: string;
                applicationMethod: string;
                frequencyRecommendation?: string;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        "entity-operation": {
            id: number;
            entityType: {
                /** @default 10 */
                id: number;
                /** @default operation */
                name: string;
                /** @default Radnje */
                label: string;
            };
            slug: string;
            attributes: {
                /** @description (jedno od: optional, once, periodic, daily, weekly, biweekly, monthly) */
                frequency?: string;
                /** @description (na koji stadij biljke se primjenjuje radnja) */
                stage: {
                    id: number;
                    information: {
                        name: string;
                        label: string;
                    };
                };
                /** @description (na što se primjenjuje operacije - jedno od: farm, garden, raisedBedFull, raisedBed1m, plant) */
                application: string;
                /** @description (broj dana kada se radi operacija relativno na životni ciklus biljke) */
                relativeDays?: number;
                /** @description (ako je radnja za dostavu, korisnik mora ugovoriti dostavu za odrađivanje ove radnje npr. Branje svih plodova) */
                deliverable: boolean;
                /** @description (vrijeme potrebno za izvršavanje radnje u minutama) */
                duration: number;
                /** @description (interna radnja se ne dojavljuje niti prikazuje korisnicima aplikacije - namjenjena je za poslove farmera) */
                internal?: boolean;
                printLabel?: boolean;
                /** @description Jedan ili više točnih tekućih pripravaka koji se mogu koristiti za ovu radnju. Koristi se kod radnji primjene/tretmana kada radnja može trošiti pripravke različitih brendova ili pakiranja. Primjer: liquidPreparation#566 za pripravak za otpornost rajčice 750 ml; kasnije se može dodati i drugi pripravak iste namjene u drugom pakiranju. */
                liquidPreparation?: {
                    id: number;
                    images?: {
                        cover?: components["schemas"]["image"];
                    };
                    information: {
                        brandName: string;
                        barcode?: string;
                        name: string;
                        label: string;
                        productUrl?: string;
                    };
                    attributes: {
                        volumeMl: number;
                        price?: number;
                        certification?: string;
                        form?: string;
                    };
                    application: {
                        dosage: string;
                        purpose: string;
                        target: string;
                        applicationMethod: string;
                        frequencyRecommendation?: string;
                    };
                }[];
                /** @description Tehnički naziv tipa entiteta čija se zaliha provjerava ili koristi kroz ovu radnju. Ovo polje služi za usmjeravanje prema pravoj evidenciji zalihe. Primjeri: farmSupply, seed, liquidPreparation. */
                inventoryEntityType?: string;
                /** @description Grupa zalihe unutar odabranog tipa entiteta. Koristi se za inventurne radnje koje broje širu skupinu zalihe, a ne samo jedan proizvod. Primjeri: raisedBedBoards, seed, plantProtection, paperDeliveryBag. */
                inventoryKind?: string;
                /** @description Jedan ili više konkretnih materijala iz tipa farmSupply koji pripadaju ovoj inventurnoj radnji. Koristi se kada jedna radnja pokriva više dobavljača, brendova, dimenzija ili pakiranja istog materijala. Primjer: farmSupply#573 za daske za gredice; kasnije se mogu dodati posebne daske drugog dobavljača ili druge dimenzije. */
                inventorySupply?: {
                    id: number;
                    images?: {
                        cover?: components["schemas"]["image"];
                    };
                    attributes: {
                        category: string;
                        kind: string;
                        packSize?: number;
                        unit: string;
                        notes?: string;
                        /** @description (cijena pakiranja u EUR) */
                        price: number;
                    };
                    information: {
                        barcode?: string;
                        name: string;
                        label: string;
                        description?: string;
                        supplier?: string;
                        productUrl?: string;
                    };
                }[];
            };
            information: {
                /** @description (puni opis operacije) */
                description: string;
                /** @description (kratki opis operacije) */
                shortDescription: string;
                /** @description (tehnički naziv operacije - jednom postavljen ne smije se mjenjati!) */
                name: string;
                /** @description (prevedeni naziv operacije) */
                label: string;
                /** @description (postupak za izvršavanje radnje) */
                instructions: string;
            };
            prices: {
                /** @description (EUR cijena za jednu operaciju) */
                perOperation: number;
                /** @description (EUR cijena s popustom) */
                discounted?: number;
                /** @description (opis popusta npr. "Za kupnju 18 biljaka") */
                discountDescription?: string;
            };
            image?: {
                cover?: components["schemas"]["image"];
            };
            conditions: {
                /** @description (da li se mogu proložiti slike za završetak radnje) */
                completionAttachImages: boolean;
                /** @description (da li je obavezno proložiti slike za završetak radnje) */
                completionAttachImagesRequired: boolean;
                /** @description (da li se mo\e priložiti napomena za završetak radnje) */
                completionAttachNotes: boolean;
                /** @description (da li je obavezno proložiti napomenu za završetak radnje) */
                completionAttachNotesRequired: boolean;
            };
            actions?: {
                removePlant?: boolean;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        "entity-operationFrequency": {
            id: number;
            entityType: {
                /** @default 13 */
                id: number;
                /** @default operationFrequency */
                name: string;
                /** @default Učestalost radnje */
                label: string;
            };
            slug: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        "entity-faq": {
            id: number;
            entityType: {
                /** @default 2 */
                id: number;
                /** @default faq */
                name: string;
                /** @default FAQ */
                label: string;
            };
            slug: string;
            information: {
                header: string;
                content: string;
                name: string;
            };
            attributes: {
                category: {
                    id: number;
                    information: {
                        name: string;
                        label: string;
                    };
                };
                tags?: string[];
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        "entity-faq-category": {
            id: number;
            entityType: {
                /** @default 14 */
                id: number;
                /** @default faq-category */
                name: string;
                /** @default FAQ Kategorija */
                label: string;
            };
            slug: string;
            information: {
                name: string;
                label: string;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        "entity-block": {
            id: number;
            entityType: {
                /** @default 8 */
                id: number;
                /** @default block */
                name: string;
                /** @default Blok */
                label: string;
            };
            slug: string;
            information: {
                name: string;
                shortDescription: string;
                fullDescription: string;
                label: string;
            };
            attributes: {
                height: number;
                stackable: boolean;
                /** @description (jedan od: decoration, raisedBed, raisedBedPart, plant, plantPart) */
                type: string;
            };
            prices: {
                sunflowers: number;
            };
            functions: {
                /** @description Blokovi koji mogu reciklirati druge blokove */
                recycler: boolean;
                /** @description Blokovi koji predstavljaju podignutu gredicu */
                raisedBed: boolean;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        "entity-farmSupply": {
            id: number;
            entityType: {
                /** @default 20 */
                id: number;
                /** @default farmSupply */
                name: string;
                /** @default Materijali i potrošni inventar */
                label: string;
            };
            slug: string;
            images?: {
                cover?: components["schemas"]["image"];
            };
            attributes: {
                category: string;
                kind: string;
                packSize?: number;
                unit: string;
                notes?: string;
                /** @description (cijena pakiranja u EUR) */
                price: number;
            };
            information: {
                barcode?: string;
                name: string;
                label: string;
                description?: string;
                supplier?: string;
                productUrl?: string;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        "entity-occasions": {
            id: number;
            entityType: {
                /** @default 17 */
                id: number;
                /** @default occasions */
                name: string;
                /** @default Natječaji */
                label: string;
            };
            slug: string;
            information: {
                name: string;
                rules: string;
                rulesChangedDate: string;
                startDate: string;
                endDate?: string;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        "entity-hqLocations": {
            id: number;
            entityType: {
                /** @default 18 */
                id: number;
                /** @default hqLocations */
                name: string;
                /** @default HQ lokacije */
                label: string;
            };
            slug: string;
            location: {
                addressStreet1: string;
                addressStreet2?: string;
                addressCity: string;
                addressZip: string;
                addressCountry: string;
                latitude: number;
                longitude: number;
            };
            information: {
                name: string;
                label: string;
            };
            delivery: {
                freeRadius: number;
                zoneRadius: number;
            };
            prices: {
                pricePerKilometer: number;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
