import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const sourcePath = join(packageRoot, 'src', 'v1.d.ts');
const outputPath = join(packageRoot, 'src', 'cms.ts');
const legacyAliases = new Map([['occasions', 'OccasionData']]);

function toPascalCase(value) {
    return value
        .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
        .split(/[^a-zA-Z0-9]+/)
        .filter(Boolean)
        .map((part) => `${part[0].toUpperCase()}${part.slice(1)}`)
        .join('');
}

function propertyKey(value) {
    return /^[A-Za-z_$][\w$]*$/.test(value) ? value : JSON.stringify(value);
}

const source = await readFile(sourcePath, 'utf8');
const entityNames = Array.from(source.matchAll(/"entity-([^"]+)":\s*\{/g))
    .map((match) => match[1])
    .filter((value, index, values) => values.indexOf(value) === index)
    .sort((left, right) => left.localeCompare(right, 'en'));

if (entityNames.length === 0) {
    throw new Error(`No CMS entity schemas found in ${sourcePath}.`);
}

const lines = [
    '// This file was generated by packages/directory-types/scripts/generateCmsTypeAliases.mjs.',
    '// Do not edit manually. Run `pnpm --filter @gredice/directory-types regenerate:cms-types`.',
    '',
    "import type { components } from './v1';",
    '',
    'export interface DirectoryEntityDataMap {',
];

for (const entityName of entityNames) {
    lines.push(
        `    ${propertyKey(entityName)}: components['schemas']['entity-${entityName}'];`,
    );
}

lines.push(
    '}',
    '',
    'export type DirectoryEntityTypeName = keyof DirectoryEntityDataMap;',
    'export type DirectoryEntityData<',
    '    TEntityTypeName extends DirectoryEntityTypeName = DirectoryEntityTypeName,',
    '> = DirectoryEntityDataMap[TEntityTypeName];',
    '',
);

for (const entityName of entityNames) {
    const typeName = `${toPascalCase(entityName)}Data`;
    lines.push(
        `export type ${typeName} = DirectoryEntityDataMap[${JSON.stringify(entityName)}];`,
    );
    const legacyAlias = legacyAliases.get(entityName);
    if (legacyAlias && legacyAlias !== typeName) {
        lines.push(`export type ${legacyAlias} = ${typeName};`);
    }
}

lines.push('');

await writeFile(outputPath, lines.join('\n'), 'utf8');
