import {
    Add,
    AI,
    Approved,
    ArrowDown,
    ArrowDownLeft,
    ArrowDownRight,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    ArrowUpLeft,
    ArrowUpRight,
    Bookmark,
    Calendar,
    Check,
    ChevronsDown,
    Close,
    Cloud,
    Comment,
    CompanyFacebook,
    Configuration,
    Copy,
    Custom,
    Delete,
    Desktop,
    Device,
    Discount,
    Down,
    Droplet,
    Droplets,
    Edit,
    Empty,
    Error as ErrorIcon,
    ExpandDown,
    ExternalLink,
    Eye,
    Fence,
    FileText,
    Footprints,
    FullWidth,
    GamepadDirectional,
    Ghost,
    Globe,
    Graph,
    Heart,
    History,
    Home,
    Hourglass,
    Info,
    Joystick,
    Laptop,
    Layers,
    LayoutGrid,
    LayoutList,
    Leaf,
    Left,
    Lightning,
    LoaderSpinner,
    LogOut,
    Mail,
    MailCheck,
    MapPin,
    MapPinHouse,
    Megaphone,
    Menu,
    Moon,
    MoreHorizontal,
    Mute,
    Navigate,
    Password,
    Play,
    Redo,
    Reset,
    Save,
    Search,
    Security,
    Send,
    Settings,
    ShoppingCart,
    Snowflake,
    SquareArrowRightEnter,
    Sun,
    SunMoon,
    Tablet,
    Thermometer,
    Timer,
    Truck,
    Undo,
    Up,
    User,
    UserCircle,
    Volume2,
    Wallet,
    Warning,
    Wind,
    ZoomIn,
    ZoomOut,
} from '@gredice/ui/icons';
import type { ComponentType } from 'react';

// Audited game and garden Lucide imports. Keep aliases separate for their distinct usage contexts.
export const gameIconUsage = [
    {
        name: 'AI',
        Icon: AI,
        lucideName: 'Sparkles',
        sources: [
            'packages/game/src/hud/DebugHud.tsx',
            'packages/game/src/hud/SuncokretChatHud.tsx',
            'packages/game/src/shared-ui/sunflowers/SunflowerPackagesPanel.tsx',
        ],
    },
    {
        name: 'Add',
        Icon: Add,
        lucideName: 'Plus',
        sources: [
            'packages/game/src/generators/plant/editor/components/CreatePlantModal.tsx',
            'packages/game/src/hud/GardenAccountMenuItems.tsx',
            'packages/game/src/hud/InventoryHud.tsx',
            'packages/game/src/hud/SuncokretChatHud.tsx',
            'packages/game/src/hud/raisedBed/RecommendationsCard.tsx',
            'packages/game/src/modals/components/AccountUsersCard.tsx',
            'packages/game/src/modals/components/GardenTab.tsx',
            'packages/game/src/shared-ui/delivery/DeliveryAddressesSection.tsx',
        ],
    },
    {
        name: 'Approved',
        Icon: Approved,
        lucideName: 'CheckCheck',
        sources: [
            'packages/game/src/hud/AccountHud.tsx',
            'packages/game/src/hud/GardenOperationsHud.tsx',
            'packages/game/src/modals/components/NotificationsTab.tsx',
            'packages/game/src/shared-ui/delivery/DeliveryStatusChip.tsx',
            'packages/game/src/shared-ui/sunflowers/DailyRewardOverview.tsx',
        ],
    },
    {
        name: 'ArrowDown',
        Icon: ArrowDown,
        lucideName: 'ArrowDown',
        sources: [
            'packages/game/src/hud/components/weather/WeatherForecastDetails.tsx',
            'packages/game/src/hud/components/weather/WeatherNowDetails.tsx',
        ],
    },
    {
        name: 'ArrowDownLeft',
        Icon: ArrowDownLeft,
        lucideName: 'ArrowDownLeft',
        sources: [
            'packages/game/src/hud/components/weather/WeatherForecastDetails.tsx',
            'packages/game/src/hud/components/weather/WeatherNowDetails.tsx',
        ],
    },
    {
        name: 'ArrowDownRight',
        Icon: ArrowDownRight,
        lucideName: 'ArrowDownRight',
        sources: [
            'packages/game/src/hud/components/weather/WeatherForecastDetails.tsx',
            'packages/game/src/hud/components/weather/WeatherNowDetails.tsx',
        ],
    },
    {
        name: 'ArrowLeft',
        Icon: ArrowLeft,
        lucideName: 'ArrowLeft',
        sources: [
            'packages/game/src/hud/SuncokretChatHud.tsx',
            'packages/game/src/hud/components/weather/WeatherForecastDetails.tsx',
            'packages/game/src/hud/components/weather/WeatherNowDetails.tsx',
            'packages/game/src/shared-ui/delivery/DeliverySlotPicker.tsx',
            'packages/game/src/viewers/OutletGardenNavigationHud.tsx',
            'packages/game/src/viewers/OutletGardenOfferBrowser.tsx',
        ],
    },
    {
        name: 'ArrowRight',
        Icon: ArrowRight,
        lucideName: 'ArrowRight',
        sources: [
            'packages/game/src/hud/components/weather/WeatherForecastDetails.tsx',
            'packages/game/src/hud/components/weather/WeatherNowDetails.tsx',
            'packages/game/src/shared-ui/delivery/DeliverySlotPicker.tsx',
        ],
    },
    {
        name: 'ArrowUp',
        Icon: ArrowUp,
        lucideName: 'ArrowUp',
        sources: [
            'packages/game/src/hud/GardenAvatarHud.tsx',
            'packages/game/src/hud/components/weather/WeatherForecastDetails.tsx',
            'packages/game/src/hud/components/weather/WeatherNowDetails.tsx',
        ],
    },
    {
        name: 'ArrowUpLeft',
        Icon: ArrowUpLeft,
        lucideName: 'ArrowUpLeft',
        sources: [
            'packages/game/src/hud/components/weather/WeatherForecastDetails.tsx',
            'packages/game/src/hud/components/weather/WeatherNowDetails.tsx',
        ],
    },
    {
        name: 'ArrowUpRight',
        Icon: ArrowUpRight,
        lucideName: 'ArrowUpRight',
        sources: [
            'packages/game/src/hud/components/weather/WeatherForecastDetails.tsx',
            'packages/game/src/hud/components/weather/WeatherNowDetails.tsx',
        ],
    },
    {
        name: 'Bookmark',
        Icon: Bookmark,
        lucideName: 'Bookmark',
        sources: [
            'packages/game/src/hud/GardenAccountMenuItems.tsx',
            'packages/game/src/hud/raisedBed/FavoriteToggleButton.tsx',
        ],
    },
    {
        name: 'Calendar',
        Icon: Calendar,
        lucideName: 'Calendar',
        sources: [
            'packages/game/src/hud/GardenOperationsHud.tsx',
            'packages/game/src/hud/SandboxEnvironmentHud.tsx',
            'packages/game/src/hud/ShoppingCartHud.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedAiOperationMarkdown.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedDiaryRescheduleAction.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedFieldStatusChange.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedPlantPicker.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedSelectedPlantingOwnerControls.tsx',
            'packages/game/src/hud/raisedBed/shared/OperationScheduleModal.tsx',
            'packages/game/src/hud/raisedBed/shared/OperationsListItem.tsx',
            'packages/game/src/shared-ui/delivery/DeliverySlotPicker.tsx',
            'packages/game/src/viewers/PublicGardenRaisedBedDetails.tsx',
        ],
    },
    {
        name: 'Check',
        Icon: Check,
        lucideName: 'Check',
        sources: [
            'packages/game/src/controls/components/SegmentedProgress.tsx',
            'packages/game/src/hud/ControlsTooltipHud.tsx',
            'packages/game/src/hud/GardenAccountMenuItems.tsx',
            'packages/game/src/hud/NotificationList.tsx',
            'packages/game/src/hud/RaisedBedFieldHud.tsx',
            'packages/game/src/hud/RaisedBedOnboardingModal.tsx',
            'packages/game/src/hud/SuncokretChatHud.tsx',
            'packages/game/src/hud/TutorialChecklistHud.tsx',
            'packages/game/src/hud/raisedBed/PlantsSortList.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedFieldItemPlanted.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedPlantPicker.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedSensorInfo.tsx',
            'packages/game/src/modals/advent/AdventDayCell.tsx',
            'packages/game/src/modals/components/GardenHomeCameraCard.tsx',
            'packages/game/src/modals/components/ReferralsTab.tsx',
            'packages/game/src/shared-ui/delivery/DeliverySlotPicker.tsx',
            'packages/game/src/shared-ui/delivery/HarvestScheduleStep.tsx',
            'packages/game/src/shared-ui/sunflowers/SunflowerPackagesPanel.tsx',
            'packages/game/src/viewers/OutletGardenCommerce.tsx',
        ],
    },
    {
        name: 'ChevronsDown',
        Icon: ChevronsDown,
        lucideName: 'ChevronsDown',
        sources: ['packages/game/src/hud/GardenAvatarHud.tsx'],
    },
    {
        name: 'Close',
        Icon: Close,
        lucideName: 'X',
        sources: [
            'packages/game/src/controls/components/SegmentedProgress.tsx',
            'packages/game/src/hud/GardenAvatarHud.tsx',
            'packages/game/src/hud/GardenTargetHighlightHud.tsx',
            'packages/game/src/hud/RaisedBedNotificationSurface.tsx',
            'packages/game/src/hud/SuncokretChatHud.tsx',
            'packages/game/src/hud/WhatsNewWidget.tsx',
            'packages/game/src/hud/components/shopping-cart/ShoppingCartItem.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedDiaryCancelAction.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedPlantPicker.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedSelectedPlantingOwnerControls.tsx',
            'packages/game/src/hud/raisedBed/shared/OperationsList.tsx',
            'packages/game/src/shared-ui/delivery/DeliveryCancelRequestModal.tsx',
            'packages/game/src/shared-ui/delivery/DeliveryRequestRow.tsx',
            'packages/game/src/shared-ui/delivery/DeliveryStatusChip.tsx',
            'packages/game/src/viewers/OutletGardenOfferBrowser.tsx',
            'packages/game/src/viewers/PublicGardenRaisedBedDetails.tsx',
        ],
    },
    {
        name: 'Cloud',
        Icon: Cloud,
        lucideName: 'Cloud',
        sources: [
            'packages/game/src/hud/DebugHud.tsx',
            'packages/game/src/hud/SandboxEnvironmentHud.tsx',
        ],
    },
    {
        name: 'Comment',
        Icon: Comment,
        lucideName: 'MessageCircle',
        sources: ['packages/game/src/hud/AccountHud.tsx'],
    },
    {
        name: 'CompanyFacebook',
        Icon: CompanyFacebook,
        lucideName: null,
        sources: [
            'packages/game/src/modals/components/FacebookLoginButton.tsx',
            'packages/game/src/modals/components/SecurityTab.tsx',
        ],
    },
    {
        name: 'Configuration',
        Icon: Configuration,
        lucideName: 'Settings2',
        sources: ['packages/game/src/hud/AccountHud.tsx'],
    },
    {
        name: 'Copy',
        Icon: Copy,
        lucideName: 'Copy',
        sources: ['packages/game/src/modals/components/ReferralsTab.tsx'],
    },
    {
        name: 'Custom',
        Icon: Custom,
        lucideName: 'Sliders',
        sources: [
            'packages/game/src/hud/DebugHud.tsx',
            'packages/game/src/hud/SandboxEnvironmentHud.tsx',
        ],
    },
    {
        name: 'Delete',
        Icon: Delete,
        lucideName: 'Trash2',
        sources: [
            'packages/game/src/generators/plant/editor/components/SettingsTab.tsx',
            'packages/game/src/hud/GardenAccountMenuItems.tsx',
            'packages/game/src/hud/ItemsHud.tsx',
            'packages/game/src/hud/ShoppingCartHud.tsx',
            'packages/game/src/hud/components/shopping-cart/ShoppingCartItem.tsx',
            'packages/game/src/modals/components/GardenDangerCard.tsx',
            'packages/game/src/shared-ui/delivery/DeliveryAddressesSection.tsx',
        ],
    },
    {
        name: 'Desktop',
        Icon: Desktop,
        lucideName: 'Monitor',
        sources: [
            'packages/game/src/hud/DebugHud.tsx',
            'packages/game/src/modals/components/NotificationsTab.tsx',
        ],
    },
    {
        name: 'Device',
        Icon: Device,
        lucideName: 'Smartphone',
        sources: ['packages/game/src/modals/components/NotificationsTab.tsx'],
    },
    {
        name: 'Discount',
        Icon: Discount,
        lucideName: 'TicketPercent',
        sources: [
            'packages/game/src/hud/components/OutletBadge.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedPlantPicker.tsx',
        ],
    },
    {
        name: 'Down',
        Icon: Down,
        lucideName: 'ChevronDown',
        sources: ['packages/game/src/hud/raisedBed/RaisedBedSensorInfo.tsx'],
    },
    {
        name: 'Droplet',
        Icon: Droplet,
        lucideName: 'Droplet',
        sources: ['packages/game/src/hud/raisedBed/RaisedBedSensorInfo.tsx'],
    },
    {
        name: 'Droplets',
        Icon: Droplets,
        lucideName: 'Droplets',
        sources: [
            'packages/game/src/hud/DebugHud.tsx',
            'packages/game/src/hud/SandboxEnvironmentHud.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedSensorInfo.tsx',
        ],
    },
    {
        name: 'Edit',
        Icon: Edit,
        lucideName: 'Edit3',
        sources: [
            'packages/game/src/generators/plant/editor/components/PlantControl.tsx',
            'packages/game/src/modals/components/ReferralsTab.tsx',
            'packages/game/src/shared-ui/delivery/DeliveryAddressesSection.tsx',
            'packages/game/src/shared-ui/delivery/DeliveryStep.tsx',
            'packages/game/src/shared-ui/delivery/HarvestScheduleStep.tsx',
        ],
    },
    {
        name: 'Empty',
        Icon: Empty,
        lucideName: 'Circle',
        sources: [
            'packages/game/src/hud/components/weather/WeatherForecastDetails.tsx',
            'packages/game/src/hud/components/weather/WeatherNowDetails.tsx',
            'packages/game/src/modals/components/NotificationsTab.tsx',
            'packages/game/src/shared-ui/sunflowers/DailyRewardOverview.tsx',
            'packages/game/src/shared-ui/sunflowers/SunflowersList.tsx',
        ],
    },
    {
        name: 'Error',
        Icon: ErrorIcon,
        lucideName: 'CircleX',
        sources: ['packages/game/src/hud/GardenOperationsHud.tsx'],
    },
    {
        name: 'ExpandDown',
        Icon: ExpandDown,
        lucideName: 'ChevronDown',
        sources: [
            'packages/game/src/hud/TutorialChecklistHud.tsx',
            'packages/game/src/hud/raisedBed/RecommendationSection.tsx',
            'packages/game/src/shared-ui/sunflowers/SunflowerPackagesPanel.tsx',
        ],
    },
    {
        name: 'ExternalLink',
        Icon: ExternalLink,
        lucideName: 'ExternalLink',
        sources: [
            'packages/game/src/hud/AccountHud.tsx',
            'packages/game/src/hud/RaisedBedOnboardingModal.tsx',
            'packages/game/src/hud/WhatsNewWidget.tsx',
            'packages/game/src/hud/raisedBed/PlantStageSection.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedFieldItemPlanted.tsx',
            'packages/game/src/modals/components/GardenVisibilityCard.tsx',
            'packages/game/src/modals/components/ReferralsTab.tsx',
            'packages/game/src/shared-ui/delivery/DeliveryRequestRow.tsx',
        ],
    },
    {
        name: 'Eye',
        Icon: Eye,
        lucideName: 'Eye',
        sources: ['packages/game/src/hud/GardenAvatarHud.tsx'],
    },
    {
        name: 'Fence',
        Icon: Fence,
        lucideName: 'Fence',
        sources: ['packages/game/src/hud/DebugHud.tsx'],
    },
    {
        name: 'FileText',
        Icon: FileText,
        lucideName: 'FileText',
        sources: ['apps/garden/app/racun/naplata/BillingPageClient.tsx'],
    },
    {
        name: 'Footprints',
        Icon: Footprints,
        lucideName: 'Footprints',
        sources: ['packages/game/src/hud/GardenAvatarHud.tsx'],
    },
    {
        name: 'FullWidth',
        Icon: FullWidth,
        lucideName: 'Maximize2',
        sources: ['packages/game/src/hud/DebugHud.tsx'],
    },
    {
        name: 'GamepadDirectional',
        Icon: GamepadDirectional,
        lucideName: 'GamepadDirectional',
        sources: ['packages/game/src/hud/ControlsTooltipHud.tsx'],
    },
    {
        name: 'Ghost',
        Icon: Ghost,
        lucideName: 'Ghost',
        sources: ['packages/game/src/hud/DebugHud.tsx'],
    },
    {
        name: 'Globe',
        Icon: Globe,
        lucideName: 'Globe',
        sources: [
            'packages/game/src/modals/components/GardenVisibilityCard.tsx',
        ],
    },
    {
        name: 'Graph',
        Icon: Graph,
        lucideName: 'ChartLine',
        sources: [
            'packages/game/src/hud/DebugHud.tsx',
            'packages/game/src/hud/components/weather/WeatherViewToggle.tsx',
        ],
    },
    {
        name: 'Heart',
        Icon: Heart,
        lucideName: 'Heart',
        sources: [
            'packages/game/src/hud/raisedBed/RaisedBedField.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedFieldRelationshipIndicator.tsx',
        ],
    },
    {
        name: 'History',
        Icon: History,
        lucideName: 'History',
        sources: [
            'packages/game/src/hud/SuncokretChatHud.tsx',
            'packages/game/src/hud/SuncokretConversationList.tsx',
        ],
    },
    {
        name: 'Home',
        Icon: Home,
        lucideName: 'Home',
        sources: [
            'packages/game/src/hud/raisedBed/GreenhouseSeedlingProgress.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedFieldItemPlanted.tsx',
        ],
    },
    {
        name: 'Hourglass',
        Icon: Hourglass,
        lucideName: 'Hourglass',
        sources: ['packages/game/src/hud/GardenOperationsHud.tsx'],
    },
    {
        name: 'Info',
        Icon: Info,
        lucideName: 'Info',
        sources: [
            'packages/game/src/generators/plant/editor/components/InfoHint.tsx',
            'packages/game/src/hud/GardenOperationsHud.tsx',
            'packages/game/src/hud/ItemsHud.tsx',
            'packages/game/src/hud/RaisedBedOnboardingModal.tsx',
            'packages/game/src/hud/ShoppingCartHud.tsx',
            'packages/game/src/hud/SunflowersHud.tsx',
            'packages/game/src/hud/components/shopping-cart/ButtonConfirmPayment.tsx',
            'packages/game/src/modals/components/ReferralsTab.tsx',
            'packages/game/src/shared-ui/delivery/DeliveryCancelRequestModal.tsx',
            'packages/game/src/shared-ui/delivery/DeliveryStatusChip.tsx',
            'packages/game/src/shared-ui/delivery/DeliveryStep.tsx',
            'packages/game/src/shared-ui/delivery/HarvestScheduleStep.tsx',
        ],
    },
    {
        name: 'Joystick',
        Icon: Joystick,
        lucideName: 'Joystick',
        sources: [
            'packages/game/src/hud/AccountHud.tsx',
            'packages/game/src/hud/GardenAccountMenuItems.tsx',
        ],
    },
    {
        name: 'Laptop',
        Icon: Laptop,
        lucideName: 'Laptop',
        sources: ['packages/game/src/modals/components/NotificationsTab.tsx'],
    },
    {
        name: 'Layers',
        Icon: Layers,
        lucideName: 'Layers2',
        sources: ['packages/game/src/hud/DebugHud.tsx'],
    },
    {
        name: 'LayoutGrid',
        Icon: LayoutGrid,
        lucideName: 'LayoutGrid',
        sources: [
            'packages/game/src/hud/AccountHud.tsx',
            'packages/game/src/hud/DebugHud.tsx',
            'packages/game/src/viewers/OutletGardenBrowserViewer.tsx',
        ],
    },
    {
        name: 'LayoutList',
        Icon: LayoutList,
        lucideName: 'LayoutList',
        sources: ['packages/game/src/viewers/OutletGardenNavigationHud.tsx'],
    },
    {
        name: 'Leaf',
        Icon: Leaf,
        lucideName: 'Leaf',
        sources: [
            'packages/game/src/generators/plant/editor/components/PlantControl.tsx',
            'packages/game/src/modals/components/SoundSettingsCard.tsx',
        ],
    },
    {
        name: 'Left',
        Icon: Left,
        lucideName: 'ChevronLeft',
        sources: [
            'packages/game/src/hud/ItemsHud.tsx',
            'packages/game/src/hud/RaisedBedOnboardingModal.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedPlantPicker.tsx',
        ],
    },
    {
        name: 'Lightning',
        Icon: Lightning,
        lucideName: 'Zap',
        sources: [
            'packages/game/src/hud/DebugHud.tsx',
            'packages/game/src/hud/SandboxEnvironmentHud.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedField.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedFieldRelationshipIndicator.tsx',
        ],
    },
    {
        name: 'LoaderSpinner',
        Icon: LoaderSpinner,
        lucideName: 'Loader2',
        sources: [
            'packages/game/src/hud/SuncokretChatHud.tsx',
            'packages/game/src/hud/SuncokretConversationList.tsx',
        ],
    },
    {
        name: 'LogOut',
        Icon: LogOut,
        lucideName: 'LogOut',
        sources: [
            'packages/game/src/hud/AccountHud.tsx',
            'packages/game/src/hud/GardenAvatarHud.tsx',
        ],
    },
    {
        name: 'Mail',
        Icon: Mail,
        lucideName: 'Mail',
        sources: [
            'apps/garden/app/prijava/EmailSentCard.tsx',
            'apps/garden/app/prijava/registracija-uspijesna/RegistrationSuccessfulContent.tsx',
            'apps/garden/components/auth/LoginModal.tsx',
        ],
    },
    {
        name: 'MailCheck',
        Icon: MailCheck,
        lucideName: 'MailCheck',
        sources: [
            'apps/garden/app/prijava/potvrda-emaila/page.tsx',
            'apps/garden/app/prijava/potvrda-emaila/posalji/page.tsx',
            'packages/game/src/hud/GardenOperationsHud.tsx',
        ],
    },
    {
        name: 'MapPin',
        Icon: MapPin,
        lucideName: 'MapPin',
        sources: [
            'packages/game/src/hud/DebugHud.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedAdvancedSowingPlantingDetails.tsx',
            'packages/game/src/shared-ui/delivery/DeliveryRequestGroupCard.tsx',
            'packages/game/src/shared-ui/delivery/DeliveryRequestRow.tsx',
            'packages/game/src/shared-ui/delivery/DeliverySlotPicker.tsx',
        ],
    },
    {
        name: 'MapPinHouse',
        Icon: MapPinHouse,
        lucideName: 'MapPinHouse',
        sources: [
            'packages/game/src/hud/GardenAccountMenuItems.tsx',
            'packages/game/src/modals/components/GardenHomeCameraCard.tsx',
        ],
    },
    {
        name: 'Megaphone',
        Icon: Megaphone,
        lucideName: 'Megaphone',
        sources: [
            'packages/game/src/GameHud.tsx',
            'packages/game/src/modals/components/NotificationsTab.tsx',
            'packages/game/src/viewers/OutletGardenSceneControlsHud.tsx',
        ],
    },
    {
        name: 'Menu',
        Icon: Menu,
        lucideName: 'Menu',
        sources: [
            'packages/game/src/generators/plant/editor/components/MobileControls.tsx',
        ],
    },
    {
        name: 'Moon',
        Icon: Moon,
        lucideName: 'Moon',
        sources: [
            'packages/game/src/hud/DebugHud.tsx',
            'packages/game/src/hud/SandboxEnvironmentHud.tsx',
        ],
    },
    {
        name: 'MoreHorizontal',
        Icon: MoreHorizontal,
        lucideName: 'MoreHorizontal',
        sources: [
            'packages/game/src/hud/raisedBed/RaisedBedFieldItemEmpty.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedFieldItemPlanted.tsx',
        ],
    },
    {
        name: 'Mute',
        Icon: Mute,
        lucideName: 'VolumeX',
        sources: ['packages/game/src/hud/AudioHud.tsx'],
    },
    {
        name: 'Navigate',
        Icon: Navigate,
        lucideName: 'ChevronRight',
        sources: [
            'packages/game/src/hud/GardenOperationsHud.tsx',
            'packages/game/src/hud/ItemsHud.tsx',
            'packages/game/src/hud/PaymentSuccessfulMessage.tsx',
            'packages/game/src/hud/RaisedBedFieldHud.tsx',
            'packages/game/src/hud/RaisedBedOnboardingModal.tsx',
            'packages/game/src/hud/ShoppingCartHud.tsx',
            'packages/game/src/hud/SunflowersHud.tsx',
            'packages/game/src/hud/components/shopping-cart/ButtonConfirmPayment.tsx',
            'packages/game/src/hud/components/shopping-cart/ShoppingCartItem.tsx',
            'packages/game/src/hud/components/weather/WeatherNowDetails.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedFieldStatusChange.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedPhotosModal.tsx',
            'packages/game/src/hud/raisedBed/RecommendationsCard.tsx',
            'packages/game/src/modals/advent/AdventAwardScreen.tsx',
            'packages/game/src/modals/advent/AdventDescriptionScreen.tsx',
            'packages/game/src/modals/advent/AdventWelcomeScreen.tsx',
            'packages/game/src/shared-ui/delivery/DeliveryRequestsSection.tsx',
            'packages/game/src/shared-ui/delivery/DeliveryStep.tsx',
            'packages/game/src/shared-ui/delivery/HarvestScheduleStep.tsx',
        ],
    },
    {
        name: 'Password',
        Icon: Password,
        lucideName: 'KeyRound',
        sources: [
            'apps/garden/app/prijava/promjena-zaporke/page.tsx',
            'apps/garden/app/prijava/promjena-zaporke/uspijeh/page.tsx',
            'apps/garden/app/prijava/zaboravljena-zaporka/page.tsx',
        ],
    },
    {
        name: 'Play',
        Icon: Play,
        lucideName: 'Play',
        sources: ['packages/game/src/modals/components/SoundSettingsCard.tsx'],
    },
    {
        name: 'Redo',
        Icon: Redo,
        lucideName: 'Redo',
        sources: [
            'packages/game/src/generators/plant/editor/components/PlantControl.tsx',
            'packages/game/src/hud/CameraHud.tsx',
            'packages/game/src/hud/controls-tooltip/RotateButton.tsx',
        ],
    },
    {
        name: 'Reset',
        Icon: Reset,
        lucideName: 'RotateCcw',
        sources: [
            'apps/garden/app/debug/animals/AnimalDebugActions.tsx',
            'apps/garden/app/debug/sandbox/SandboxDebugActions.tsx',
            'packages/game/src/generators/plant/editor/components/SettingsTab.tsx',
            'packages/game/src/hud/DebugHud.tsx',
            'packages/game/src/hud/SandboxEnvironmentHud.tsx',
            'packages/game/src/modals/components/SoundSettingsCard.tsx',
            'packages/game/src/viewers/OutletGardenCommerce.tsx',
            'packages/game/src/viewers/OutletGardenOfferBrowser.tsx',
        ],
    },
    {
        name: 'Save',
        Icon: Save,
        lucideName: 'Save',
        sources: [
            'packages/game/src/generators/plant/editor/components/ExportDialog.tsx',
            'packages/game/src/hud/AccountHud.tsx',
        ],
    },
    {
        name: 'Search',
        Icon: Search,
        lucideName: 'Search',
        sources: [
            'packages/game/src/hud/raisedBed/RaisedBedPlantPicker.tsx',
            'packages/game/src/hud/raisedBed/shared/OperationsList.tsx',
        ],
    },
    {
        name: 'Security',
        Icon: Security,
        lucideName: 'ShieldCheck',
        sources: ['packages/game/src/modals/components/SecurityTab.tsx'],
    },
    {
        name: 'Send',
        Icon: Send,
        lucideName: 'Send',
        sources: ['packages/game/src/hud/SuncokretChatHud.tsx'],
    },
    {
        name: 'Settings',
        Icon: Settings,
        lucideName: 'Settings',
        sources: [
            'packages/game/src/generators/plant/editor/components/PlantControl.tsx',
            'packages/game/src/hud/DebugHud.tsx',
        ],
    },
    {
        name: 'ShoppingCart',
        Icon: ShoppingCart,
        lucideName: 'ShoppingBasket',
        sources: [
            'packages/game/src/hud/GardenOperationsHud.tsx',
            'packages/game/src/hud/RaisedBedOnboardingModal.tsx',
            'packages/game/src/hud/SunflowersHud.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedFieldItemEmpty.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedPlantPicker.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedSensorInfo.tsx',
            'packages/game/src/hud/raisedBed/shared/OperationsListItem.tsx',
            'packages/game/src/shared-ui/delivery/DeliveryCancelRequestModal.tsx',
            'packages/game/src/shared-ui/delivery/DeliveryRequestGroupCard.tsx',
            'packages/game/src/shared-ui/delivery/DeliveryRequestRow.tsx',
            'packages/game/src/shared-ui/sunflowers/SunflowersList.tsx',
        ],
    },
    {
        name: 'Snowflake',
        Icon: Snowflake,
        lucideName: 'Snowflake',
        sources: [
            'packages/game/src/hud/DebugHud.tsx',
            'packages/game/src/hud/SandboxEnvironmentHud.tsx',
            'packages/game/src/hud/components/weather/WeatherNowDetails.tsx',
        ],
    },
    {
        name: 'SquareArrowRightEnter',
        Icon: SquareArrowRightEnter,
        lucideName: 'SquareArrowRightEnter',
        sources: ['packages/game/src/hud/TemporaryAccountAuthHud.tsx'],
    },
    {
        name: 'Sun',
        Icon: Sun,
        lucideName: 'Sun',
        sources: [
            'packages/game/src/hud/DebugHud.tsx',
            'packages/game/src/hud/SandboxEnvironmentHud.tsx',
            'packages/game/src/hud/SuncokretChatHud.tsx',
            'packages/game/src/hud/components/weather/WeatherViewToggle.tsx',
        ],
    },
    {
        name: 'SunMoon',
        Icon: SunMoon,
        lucideName: 'SunMoon',
        sources: [
            'packages/game/src/hud/DebugHud.tsx',
            'packages/game/src/hud/SandboxEnvironmentHud.tsx',
        ],
    },
    {
        name: 'Tablet',
        Icon: Tablet,
        lucideName: 'Tablet',
        sources: ['packages/game/src/modals/components/NotificationsTab.tsx'],
    },
    {
        name: 'Thermometer',
        Icon: Thermometer,
        lucideName: 'Thermometer',
        sources: [
            'packages/game/src/hud/DebugHud.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedSensorInfo.tsx',
        ],
    },
    {
        name: 'Timer',
        Icon: Timer,
        lucideName: 'Timer',
        sources: [
            'packages/game/src/hud/components/shopping-cart/ShoppingCartItem.tsx',
            'packages/game/src/shared-ui/delivery/DeliveryRequestGroupCard.tsx',
            'packages/game/src/shared-ui/delivery/DeliveryRequestRow.tsx',
            'packages/game/src/shared-ui/delivery/DeliveryStatusChip.tsx',
        ],
    },
    {
        name: 'Truck',
        Icon: Truck,
        lucideName: 'Truck',
        sources: [
            'packages/game/src/hud/ShoppingCartHud.tsx',
            'packages/game/src/shared-ui/delivery/DeliveryCancelRequestModal.tsx',
            'packages/game/src/shared-ui/delivery/DeliveryRequestGroupCard.tsx',
            'packages/game/src/shared-ui/delivery/DeliveryRequestRow.tsx',
            'packages/game/src/shared-ui/delivery/DeliveryRequestsSection.tsx',
            'packages/game/src/shared-ui/delivery/DeliverySlotPicker.tsx',
        ],
    },
    {
        name: 'Undo',
        Icon: Undo,
        lucideName: 'Undo',
        sources: [
            'packages/game/src/generators/plant/editor/components/PlantControl.tsx',
            'packages/game/src/hud/CameraHud.tsx',
            'packages/game/src/hud/controls-tooltip/RotateButton.tsx',
        ],
    },
    {
        name: 'Up',
        Icon: Up,
        lucideName: 'ChevronUp',
        sources: [
            'packages/game/src/hud/ItemsHud.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedSensorInfo.tsx',
        ],
    },
    {
        name: 'User',
        Icon: User,
        lucideName: 'User',
        sources: ['packages/game/src/hud/AccountHud.tsx'],
    },
    {
        name: 'UserCircle',
        Icon: UserCircle,
        lucideName: 'UserCircle',
        sources: ['packages/game/src/hud/GardenAvatarHud.tsx'],
    },
    {
        name: 'Volume2',
        Icon: Volume2,
        lucideName: 'Volume2',
        sources: ['packages/game/src/hud/AudioHud.tsx'],
    },
    {
        name: 'Wallet',
        Icon: Wallet,
        lucideName: 'Wallet',
        sources: ['apps/garden/app/racun/naplata/BillingPageClient.tsx'],
    },
    {
        name: 'Warning',
        Icon: Warning,
        lucideName: 'AlertTriangle',
        sources: [
            'apps/garden/app/prijava/potvrda-emaila/VerifyEmail.tsx',
            'packages/game/src/hud/SuncokretChatHud.tsx',
            'packages/game/src/hud/WeatherHud.tsx',
            'packages/game/src/hud/components/weather/WeatherNowDetails.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedDiaryCancelAction.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedFieldItemPlanted.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedSensorInfo.tsx',
            'packages/game/src/modals/components/GardenDangerCard.tsx',
            'packages/game/src/modals/components/GardenHomeCameraCard.tsx',
            'packages/game/src/modals/components/GardenTab.tsx',
            'packages/game/src/modals/components/GardenVisibilityCard.tsx',
            'packages/game/src/modals/components/RaisedBedAbandonCard.tsx',
        ],
    },
    {
        name: 'Wind',
        Icon: Wind,
        lucideName: 'Wind',
        sources: [
            'packages/game/src/hud/DebugHud.tsx',
            'packages/game/src/hud/SandboxEnvironmentHud.tsx',
            'packages/game/src/hud/components/weather/WeatherForecastDetails.tsx',
            'packages/game/src/hud/components/weather/WeatherNowDetails.tsx',
        ],
    },
    {
        name: 'ZoomIn',
        Icon: ZoomIn,
        lucideName: 'ZoomIn',
        sources: ['packages/game/src/hud/GardenAvatarHud.tsx'],
    },
    {
        name: 'ZoomOut',
        Icon: ZoomOut,
        lucideName: 'ZoomOut',
        sources: ['packages/game/src/hud/GardenAvatarHud.tsx'],
    },
] satisfies {
    name: string;
    Icon: ComponentType<{ className?: string }>;
    lucideName: string | null;
    sources: string[];
}[];
