export const KnownPages = {
    Dashboard: '/admin',
    Directories: '/admin/directories',
    DirectoryEntityType: (entityTypeName: string) => `/admin/directories/${entityTypeName}`,
    DirectoryEntityTypeEdit: (entityTypeName: string) => `/admin/directories/${entityTypeName}/edit`,
    DirectoryEntityTypeCreate: '/admin/directories/entity-types/create',
    DirectoryEntityTypeAttributeDefinitions: (entityTypeName: string) => `/admin/directories/${entityTypeName}/attribute-definitions`,
    DirectoryEntityTypeAttributeDefinitionCategory: (entityTypeName: string, id: number) => `/admin/directories/${entityTypeName}/attribute-definitions/categories/${id}`,
    DirectoryEntityTypeAttributeDefinition: (entityTypeName: string, id: number) => `/admin/directories/${entityTypeName}/attribute-definitions/${id}`,
    DirectoryEntity: (entityTypeName: string, entityId: number) => `/admin/directories/${entityTypeName}/${entityId}`,
    DirectoryEntityPath: '/admin/directories/[entityType]/[entityId]',
    DirectoryCategoryCreate: '/admin/directories/categories/create',
    DirectoryCategoryEdit: (categoryId: number) => `/admin/directories/categories/${categoryId}/edit`,
    Users: '/admin/users',
    User: (userId: string) => `/admin/users/${userId}`,
    Schedule: '/admin/schedule',
    Accounts: '/admin/accounts',
    Account: (accountId: string) => `/admin/accounts/${accountId}`,
    Gardens: '/admin/gardens',
    Garden: (gardenId: number) => `/admin/gardens/${gardenId}`,
    CommunicationInbox: '/admin/communication/inbox',
    Feedback: '/admin/feedback',
    Logout: '/admin/logout',
    RaisedBeds: '/admin/raised-beds',
    RaisedBed: (raisedBedId: number) => `/admin/raised-beds/${raisedBedId}`,
    Transactions: '/admin/transactions',
    Transaction: (transactionId: number) => `/admin/transactions/${transactionId}`,
    Invoices: '/admin/invoices',
    CreateInvoice: '/admin/invoices/create',
    Invoice: (invoiceId: number) => `/admin/invoices/${invoiceId}`,
    Receipts: '/admin/receipts',
    Receipt: (receiptId: number) => `/admin/receipts/${receiptId}`,
    ShoppingCarts: '/admin/shopping-carts',
    ShoppingCart: (cartId: number) => `/admin/shopping-carts/${cartId}`,
    Operations: '/admin/operations',
    Sensors: '/admin/sensors',
    Cache: '/admin/cache',

    // External links
    StripePayment: (paymentId: string) => `https://dashboard.stripe.com/payments/${paymentId}`,
    GrediceOperations: `https://www.gredice.com/radnje`,
    GrediceOperation: (operationAlias: string) => `https://www.gredice.com/radnje/${encodeURIComponent(operationAlias)}`,
}
