export const KnownPages = {
    Dashboard: '/admin',
    Directories: '/admin/directories',
    DirectoryEntityType: (entityTypeName: string) => `/admin/directories/${entityTypeName}`,
    DirectoryEntityTypeAttributeDefinitions: (entityTypeName: string) => `/admin/directories/${entityTypeName}/attribute-definitions`,
    DirectoryEntityTypeAttributeDefinition: (entityTypeName: string, id: number) => `/admin/directories/${entityTypeName}/attribute-definitions/${id}`,
    DirectoryEntityTypeAttributeDefinitionCategory: (entityTypeName: string, id: number) => `/admin/directories/${entityTypeName}/attribute-definitions/categories/${id}`,
    DirectoryEntity: (entityTypeName: string, entityId: number) => `/admin/directories/${entityTypeName}/${entityId}`,
    DirectoryEntityPath: '/admin/directories/[entityType]/[entityId]',
    Users: '/admin/users',
    User: (userId: string) => `/admin/users/${userId}`,
    Schedule: '/admin/schedule',
    Accounts: '/admin/accounts',
    Account: (accountId: string) => `/admin/accounts/${accountId}`,
    Gardens: '/admin/gardens',
    Garden: (gardenId: number) => `/admin/gardens/${gardenId}`,
    CommunicationInbox: '/admin/communication/inbox',
    Feedback: '/admin/feedback',
    Logout: '/admin/logout',
    RaisedBeds: '/admin/raised-beds',
    RaisedBed: (raisedBedId: number) => `/admin/raised-beds/${raisedBedId}`,
    Transactions: '/admin/transactions',
    Transaction: (transactionId: number) => `/admin/transactions/${transactionId}`,
    ShoppingCarts: '/admin/shopping-carts',
    ShoppingCart: (cartId: number) => `/admin/shopping-carts/${cartId}`,
    Cache: '/admin/cache',

    // External links
    StripePayment: (paymentId: string) => `https://dashboard.stripe.com/payments/${paymentId}`,
}
