import {
    GameBasketIcon,
    GameBlocksIcon,
    GameBlossomIcon,
    GameCalendarIcon,
    GameCloudIcon,
    GameCommunityIcon,
    GameGlobeIcon,
    GameHarvestIcon,
    GameIdeaIcon,
    GameLeafIcon,
    GameLocationIcon,
    GameMarketStallIcon,
    GameMoonIcon,
    GamePawIcon,
    GamePetHomeIcon,
    GamePlantDiseaseIcon,
    GamePlantPestIcon,
    GameRulerIcon,
    GameSearchIcon,
    GameSnowflakeIcon,
    GameSoilIcon,
    GameSowingDepthIcon,
    GameSunIcon,
    GameTagIcon,
    GameTimerIcon,
    GameWeightIcon,
} from '@gredice/ui/GameIcons';

export const publicVisualIcons = [
    {
        name: 'GameRulerIcon',
        Icon: GameRulerIcon,
        usage: 'Plant spacing and block height',
        path: 'apps/www/app/biljke/[alias]/SowingAttributeCards.tsx',
    },
    {
        name: 'GameSoilIcon',
        Icon: GameSoilIcon,
        usage: 'Plant soil composition',
        path: 'apps/www/app/biljke/[alias]/GrowthAttributeCards.tsx',
    },
    {
        name: 'GameSowingDepthIcon',
        Icon: GameSowingDepthIcon,
        usage: 'Sowing depth: composed soil and ruler',
        path: 'apps/www/app/biljke/[alias]/SowingAttributeCards.tsx',
    },
    {
        name: 'GameTimerIcon',
        Icon: GameTimerIcon,
        usage: 'Germination time and operation duration',
        path: 'apps/www/app/radnje/[alias]/OperationAttributesCards.tsx',
    },
    {
        name: 'GameWeightIcon',
        Icon: GameWeightIcon,
        usage: 'Seed packet weight',
        path: 'apps/www/app/sjeme/[slug]/SeedAttributeCards.tsx',
    },
    {
        name: 'GameTagIcon',
        Icon: GameTagIcon,
        usage: 'Product identifier decoration; real barcode remains unchanged',
        path: 'apps/www/app/sjeme/[slug]/SeedAttributeCards.tsx',
    },
    {
        name: 'GamePawIcon',
        Icon: GamePawIcon,
        usage: 'Pet habits and introductions',
        path: 'apps/www/app/blokovi/ljubimci/GardenPetCard.tsx',
    },
    {
        name: 'GamePetHomeIcon',
        Icon: GamePetHomeIcon,
        usage: 'Generic pet shelter information',
        path: 'apps/www/app/blokovi/ljubimci/GardenPetsIntro.tsx',
    },
    {
        name: 'GameMarketStallIcon',
        Icon: GameMarketStallIcon,
        usage: 'Producer and unavailable brand logo',
        path: 'apps/www/app/sjeme/BrandLogo.tsx',
    },
    {
        name: 'GameBlocksIcon',
        Icon: GameBlocksIcon,
        usage: 'Building block search fallback and empty catalogue',
        path: 'packages/ui/src/PublicChrome/DirectorySearchResultVisual.tsx',
    },
    {
        name: 'GameCloudIcon',
        Icon: GameCloudIcon,
        usage: 'Reused weather artwork: pet shelter routines',
        path: 'apps/www/app/blokovi/ljubimci/GardenPetCard.tsx',
    },
    {
        name: 'GameSearchIcon',
        Icon: GameSearchIcon,
        usage: 'Reused magnifier: search introduction',
        path: 'apps/www/app/pretraga/page.tsx',
    },
    {
        name: 'GameBlossomIcon',
        Icon: GameBlossomIcon,
        usage: 'Reused lifecycle flower: operation category',
        path: 'packages/ui/src/OperationImage/OperationImage.tsx',
    },
    {
        name: 'GameLeafIcon',
        Icon: GameLeafIcon,
        usage: 'Plant nutrition and growth',
        path: 'apps/www/app/biljke/[alias]/GrowthAttributeCards.tsx',
    },
    {
        name: 'GameLocationIcon',
        Icon: GameLocationIcon,
        usage: 'Delivery availability and pickup slots',
        path: 'apps/www/app/dostava/termini/page.tsx',
    },
    {
        name: 'GameCommunityIcon',
        Icon: GameCommunityIcon,
        usage: 'About: community values',
        path: 'apps/www/app/o-nama/page.tsx',
    },
    {
        name: 'GameGlobeIcon',
        Icon: GameGlobeIcon,
        usage: 'About: accessibility',
        path: 'apps/www/app/o-nama/page.tsx',
    },
    {
        name: 'GameIdeaIcon',
        Icon: GameIdeaIcon,
        usage: 'About: technology; helpful information',
        path: 'apps/www/app/o-nama/page.tsx',
    },
    {
        name: 'GamePlantDiseaseIcon',
        Icon: GamePlantDiseaseIcon,
        usage: 'Generic plant disease category',
        path: 'apps/www/components/plant-health/PlantHealthIssueDetail.tsx',
    },
    {
        name: 'GamePlantPestIcon',
        Icon: GamePlantPestIcon,
        usage: 'Generic plant pest category',
        path: 'apps/www/components/plant-health/PlantHealthIssueCard.tsx',
    },
    {
        name: 'GameCalendarIcon',
        Icon: GameCalendarIcon,
        usage: 'Reused lifecycle calendar: sowing and delivery',
        path: 'apps/www/app/sjetva/page.tsx',
    },
    {
        name: 'GameBasketIcon',
        Icon: GameBasketIcon,
        usage: 'Reused shopping basket: MCP actions',
        path: 'apps/www/app/mcp/page.tsx',
    },
    {
        name: 'GameHarvestIcon',
        Icon: GameHarvestIcon,
        usage: 'Reused harvest crate: expected yield',
        path: 'apps/www/app/biljke/[alias]/HarvestAttributeCards.tsx',
    },
    {
        name: 'GameSunIcon',
        Icon: GameSunIcon,
        usage: 'Shared weather artwork: light and seasons',
        path: 'apps/www/components/WinterModeToggle.tsx',
    },
    {
        name: 'GameMoonIcon',
        Icon: GameMoonIcon,
        usage: 'Shared weather artwork: night',
        path: 'packages/game/src/hud/components/weather/icons/WeatherArtwork.tsx',
    },
    {
        name: 'GameSnowflakeIcon',
        Icon: GameSnowflakeIcon,
        usage: 'Shared weather artwork: winter',
        path: 'apps/www/components/WinterModeToggle.tsx',
    },
];
