/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/assets/models/GameAssets.glb --types --output ../../packages/game/src/models/GameAssets.tsx 
*/

import { useGLTF } from '@react-three/drei';
import type { JSX } from 'react';
import type * as THREE from 'three';
import type { GLTF } from 'three-stdlib';

export type GLTFResult = GLTF & {
    nodes: {
        Block_Ground_1_1: THREE.Mesh;
        Block_Ground_1_2: THREE.Mesh;
        Block_Ground_2_1: THREE.Mesh;
        Block_Ground_2_2: THREE.Mesh;
        Block_Grass_1_1: THREE.Mesh;
        Block_Grass_1_2: THREE.Mesh;
        Block_Sand: THREE.Mesh;
        Raised_Bed_O_1: THREE.Mesh;
        Raised_Bed_O_2: THREE.Mesh;
        Raised_Bed_I_1: THREE.Mesh;
        Raised_Bed_I_2: THREE.Mesh;
        Raised_Bed_L_1: THREE.Mesh;
        Raised_Bed_L_2: THREE.Mesh;
        Raised_Bed_U_1: THREE.Mesh;
        Raised_Bed_U_2: THREE.Mesh;
        Raised_Bed_I_Construction_1: THREE.Mesh;
        Raised_Bed_I_Construction_2: THREE.Mesh;
        Gound_Cube: THREE.Mesh;
        Grass_1: THREE.Mesh;
        Stool: THREE.Mesh;
        Bucket_1: THREE.Mesh;
        Bucket_2: THREE.Mesh;
        Bucket_3: THREE.Mesh;
        ['Bucket_-_Handle']: THREE.Mesh;
        Stone_Small: THREE.Mesh;
        Stone_Medium: THREE.Mesh;
        Stone_Large: THREE.Mesh;
        Composter_1: THREE.Mesh;
        Composter_2: THREE.Mesh;
        Bush_1_1: THREE.Mesh;
        Bush_1_2: THREE.Mesh;
        Tree_1_1: THREE.Mesh;
        Tree_1_2: THREE.Mesh;
        Tree_1_3: THREE.Mesh;
        Fence_Corner: THREE.Mesh;
        Fence_Cross: THREE.Mesh;
        Fence_Middle: THREE.Mesh;
        Fence_Single: THREE.Mesh;
        Fence_Solo: THREE.Mesh;
        Fence_T: THREE.Mesh;
        Shade_S: THREE.Mesh;
        Shade_Single_Left: THREE.Mesh;
        Shade_Solo: THREE.Mesh;
        Shade_W: THREE.Mesh;
        Shade_E: THREE.Mesh;
        Shade_N: THREE.Mesh;
        Shade_Single_Right: THREE.Mesh;
        Shade_Middle: THREE.Mesh;
        Stick: THREE.Mesh;
        Seed: THREE.Mesh;
    };
    materials: {
        ['Material.Dirt']: THREE.MeshStandardMaterial;
        ['Material.Stone']: THREE.MeshStandardMaterial;
        ['Material.GrassPart']: THREE.MeshStandardMaterial;
        ['Material.Grass']: THREE.MeshStandardMaterial;
        ['Material.Sand']: THREE.MeshStandardMaterial;
        ['Material.Planks']: THREE.MeshStandardMaterial;
        ['Material.Water']: THREE.MeshStandardMaterial;
        ['Material.Metal']: THREE.MeshStandardMaterial;
        ['Material.Stone.001']: THREE.MeshStandardMaterial;
        ['Material.Stone.002']: THREE.MeshStandardMaterial;
        ['Material.Leaves']: THREE.MeshStandardMaterial;
    };
};

export function Model(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF(
        '/GameAssets.glb',
    ) as unknown as GLTFResult;
    return (
        <group {...props} dispose={null}>
            <group position={[0, 1, 0]}>
                <mesh
                    geometry={nodes.Block_Ground_1_1.geometry}
                    material={materials['Material.Dirt']}
                />
                <mesh
                    geometry={nodes.Block_Ground_1_2.geometry}
                    material={materials['Material.Stone']}
                />
            </group>
            <group position={[0, 1, 0]}>
                <mesh
                    geometry={nodes.Block_Ground_2_1.geometry}
                    material={materials['Material.Dirt']}
                />
                <mesh
                    geometry={nodes.Block_Ground_2_2.geometry}
                    material={materials['Material.Stone']}
                />
            </group>
            <group position={[0, 0.2, 0]}>
                <mesh
                    geometry={nodes.Block_Grass_1_1.geometry}
                    material={materials['Material.GrassPart']}
                />
                <mesh
                    geometry={nodes.Block_Grass_1_2.geometry}
                    material={materials['Material.Grass']}
                />
            </group>
            <mesh
                geometry={nodes.Block_Sand.geometry}
                material={materials['Material.Sand']}
                position={[0, 0.2, 0]}
            />
            <group position={[0, 1, 0]}>
                <mesh
                    geometry={nodes.Raised_Bed_O_1.geometry}
                    material={materials['Material.Planks']}
                />
                <mesh
                    geometry={nodes.Raised_Bed_O_2.geometry}
                    material={materials['Material.Dirt']}
                />
            </group>
            <group position={[0, 1, 0]}>
                <mesh
                    geometry={nodes.Raised_Bed_I_1.geometry}
                    material={materials['Material.Dirt']}
                />
                <mesh
                    geometry={nodes.Raised_Bed_I_2.geometry}
                    material={materials['Material.Planks']}
                />
            </group>
            <group position={[0, 1, 0]}>
                <mesh
                    geometry={nodes.Raised_Bed_L_1.geometry}
                    material={materials['Material.Dirt']}
                />
                <mesh
                    geometry={nodes.Raised_Bed_L_2.geometry}
                    material={materials['Material.Planks']}
                />
            </group>
            <group position={[0, 1, 0]}>
                <mesh
                    geometry={nodes.Raised_Bed_U_1.geometry}
                    material={materials['Material.Dirt']}
                />
                <mesh
                    geometry={nodes.Raised_Bed_U_2.geometry}
                    material={materials['Material.Planks']}
                />
            </group>
            <mesh
                geometry={nodes.Gound_Cube.geometry}
                material={materials['Material.Grass']}
                position={[0, -0.5, 0]}
                scale={0.5}
            />
            <mesh
                geometry={nodes.Grass_1.geometry}
                material={nodes.Grass_1.material}
                position={[0.021, 0, -0.246]}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                geometry={nodes.Stool.geometry}
                material={materials['Material.Planks']}
                position={[0, 1, 0]}
            />
            <group scale={[0.3, 0.25, 0.3]}>
                <mesh
                    geometry={nodes.Bucket_1.geometry}
                    material={materials['Material.Water']}
                />
                <mesh
                    geometry={nodes.Bucket_2.geometry}
                    material={materials['Material.Metal']}
                />
                <mesh
                    geometry={nodes.Bucket_3.geometry}
                    material={materials['Material.Planks']}
                />
                <mesh
                    geometry={nodes['Bucket_-_Handle'].geometry}
                    material={nodes['Bucket_-_Handle'].material}
                    scale={[3.333, 4, 3.333]}
                />
            </group>
            <mesh
                geometry={nodes.Stone_Small.geometry}
                material={materials['Material.Stone']}
                scale={0.165}
            />
            <mesh
                geometry={nodes.Stone_Medium.geometry}
                material={materials['Material.Stone.001']}
                scale={[0.236, 0.269, 0.205]}
            />
            <mesh
                geometry={nodes.Stone_Large.geometry}
                material={materials['Material.Stone.002']}
                scale={[0.263, 0.426, 0.291]}
            />
            <group
                position={[-0.002, 0.006, 0.015]}
                scale={[0.263, 0.25, 0.25]}
            >
                <mesh
                    geometry={nodes.Bush_1_1.geometry}
                    material={materials['Material.Leaves']}
                />
                <mesh
                    geometry={nodes.Bush_1_2.geometry}
                    material={materials['Material.GrassPart']}
                />
            </group>
            <group position={[0, 0.5, 0]} scale={[0.125, 0.5, 0.125]}>
                <mesh
                    geometry={nodes.Tree_1_1.geometry}
                    material={materials['Material.Planks']}
                />
                <mesh
                    geometry={nodes.Tree_1_2.geometry}
                    material={materials['Material.Leaves']}
                />
                <mesh
                    geometry={nodes.Tree_1_3.geometry}
                    material={materials['Material.GrassPart']}
                />
            </group>
            <mesh
                geometry={nodes.Fence_Corner.geometry}
                material={materials['Material.Planks']}
                position={[0, 1, 0]}
            />
            <mesh
                geometry={nodes.Fence_Cross.geometry}
                material={materials['Material.Planks']}
                position={[0, 1, 0]}
            />
            <mesh
                geometry={nodes.Fence_Middle.geometry}
                material={materials['Material.Planks']}
                position={[0, 1, 0]}
            />
            <mesh
                geometry={nodes.Fence_Single.geometry}
                material={materials['Material.Planks']}
                position={[0, 1, 0]}
            />
            <mesh
                geometry={nodes.Fence_Solo.geometry}
                material={materials['Material.Planks']}
                position={[0, 1, 0]}
            />
            <mesh
                geometry={nodes.Fence_T.geometry}
                material={materials['Material.Planks']}
                position={[0, 1, 0]}
            />
            <mesh
                geometry={nodes.Shade_S.geometry}
                material={materials['Material.Planks']}
                position={[0, 1, 0]}
            />
            <mesh
                geometry={nodes.Shade_Single_Left.geometry}
                material={materials['Material.Planks']}
                position={[0, 1, 0]}
            />
            <mesh
                geometry={nodes.Shade_Solo.geometry}
                material={materials['Material.Planks']}
                position={[0, 1, 0]}
            />
            <mesh
                geometry={nodes.Shade_W.geometry}
                material={materials['Material.Planks']}
                position={[0, 1, 0]}
            />
            <mesh
                geometry={nodes.Shade_E.geometry}
                material={materials['Material.Planks']}
                position={[0, 1, 0]}
            />
            <mesh
                geometry={nodes.Shade_N.geometry}
                material={materials['Material.Planks']}
                position={[0, 1, 0]}
            />
            <mesh
                geometry={nodes.Shade_Single_Right.geometry}
                material={nodes.Shade_Single_Right.material}
                position={[0, 1, 0]}
            />
            <mesh
                geometry={nodes.Shade_Middle.geometry}
                material={materials['Material.Planks']}
                position={[0, 1, 0]}
            />
            <mesh
                geometry={nodes.Stick.geometry}
                material={nodes.Stick.material}
            />
            <mesh
                geometry={nodes.Seed.geometry}
                material={nodes.Seed.material}
            />
            <mesh
                geometry={nodes.Raised_Bed_I_Construction_1.geometry}
                material={materials['Material.Dirt']}
            />
            <mesh
                geometry={nodes.Raised_Bed_I_Construction_2.geometry}
                material={materials['Material.Planks']}
            />
            <mesh
                geometry={nodes.Composter_1.geometry}
                material={materials['Material.Dirt']}
            />
            <mesh
                geometry={nodes.Composter_2.geometry}
                material={materials['Material.Planks']}
            />
        </group>
    );
}

useGLTF.preload('/GameAssets.glb');
