export const knownEventTypes = {
    accounts: {
        create: 'account.create',
        assignUser: 'account.assignUser',
        earnSunflowers: 'account.earnSunflowers',
        sunflowerDropSpawn: 'account.sunflowerDrop.spawn',
        earnSunflowerDrop: 'account.earnSunflowerDrop',
        referral: 'account.referral.v1',
        spendSunflowers: 'account.spendSunflowers',
        aiRequest: 'account.aiRequest',
    },
    users: {
        create: 'user.create',
        birthdayReward: 'user.birthdayReward',
    },
    gardens: {
        create: 'garden.create',
        rename: 'garden.rename',
        delete: 'garden.delete',
        blockPlace: 'garden.blockPlace',
    },
    transactions: {
        create: 'transaction.create',
        update: 'transaction.update',
        delete: 'transaction.delete',
    },
    invoices: {
        create: 'invoice.create',
        update: 'invoice.update',
        delete: 'invoice.delete',
        paid: 'invoice.paid',
    },
    receipts: {
        create: 'receipt.create',
        update: 'receipt.update',
        fiscalize: 'receipt.fiscalize',
    },
    raisedBeds: {
        create: 'raisedBed.create',
        place: 'raisedBed.place',
        delete: 'raisedBed.delete',
        abandon: 'raisedBed.abandon',
        aiAnalysis: 'raisedBed.aiAnalysis',
        weedStateSet: 'raisedBed.weedState.set',
    },
    raisedBedFields: {
        create: 'raisedBedField.create',
        delete: 'raisedBedField.delete',
        plantPlace: 'raisedBedField.plantPlace',
        plantSchedule: 'raisedBedField.plantSchedule',
        plantUpdate: 'raisedBedField.plantUpdate',
        plantBlock: 'raisedBedField.plantBlock',
        plantReplaceSort: 'raisedBedField.plantReplaceSort',
        aiAnalysis: 'raisedBedField.aiAnalysis',
        weedStateSet: 'raisedBedField.weedState.set',
    },
    operations: {
        acceptance: 'operation.acceptance',
        assign: 'operation.assign',
        entityChange: 'operation.entityChange',
        schedule: 'operation.schedule',
        complete: 'operation.complete',
        block: 'operation.block',
        completionEvidenceUpdate: 'operation.completionEvidence.update',
        verify: 'operation.verify',
        fail: 'operation.fail',
        cancel: 'operation.cancel',
    },
    approvalRequests: {
        create: 'approvalRequest.create',
        approve: 'approvalRequest.approve',
        reject: 'approvalRequest.reject',
    },
    delivery: {
        requestCreated: 'delivery.request.created',
        requestSlotChanged: 'delivery.request.slot.changed',
        requestAddressChanged: 'delivery.request.address.changed',
        requestConfirmed: 'delivery.request.confirmed',
        requestPreparing: 'delivery.request.preparing',
        requestReady: 'delivery.request.ready',
        requestReadyEmailProcessed: 'delivery.request.ready.email_processed',
        requestCancelled: 'delivery.request.cancelled',
        requestFulfilled: 'delivery.request.fulfilled',
        requestSurveySent: 'delivery.request.survey_sent',
        userCancelled: 'delivery.request.user_cancelled',
    },
    occasions: {
        adventCalendarOpen: 'occasion.advent.calendar.open',
    },
    inventory: {
        add: 'inventory.add',
        consume: 'inventory.consume',
    },
    payouts: {
        requested: 'payout.requested',
        approved: 'payout.approved',
        rejected: 'payout.rejected',
        paid: 'payout.paid',
    },
    tutorialChecklist: {
        taskReady: 'tutorialChecklist.task.ready',
    },
} as const;
