import type { PlantDefinition } from '../plant-definition-types';
import { createDevelopmentProgram, createPlant } from './helpers';

const cucurbitAppearance = {
    height: 0.74,
    stem: {
        color: '#4f7028',
        radius: 0.028,
        radiusDecay: 0.42,
        minRadius: 0.004,
    },
    leaf: {
        color: '#567f2a',
        size: 0.38,
        type: 'palmate',
    },
    flower: {
        enabled: true,
        color: '#f5e642',
        size: 0.09,
    },
} satisfies Pick<PlantDefinition, 'flower' | 'height' | 'leaf' | 'stem'>;

export const cucurbitPlants = {
    cucumber: createPlant('cucumber', {
        ...cucurbitAppearance,
        name: 'Krastavac',
        height: 0.82,
        development: createDevelopmentProgram('vine', {
            axes: {
                branchCount: 4,
                branchLengthScale: 0.4,
                branchNodeCount: 2,
                branchPitchDegrees: 22,
                habit: 'climbing',
                nodeCount: 11,
                pitchDegrees: 68,
                spread: 0.32,
            },
            foliage: {
                count: 13,
                emergenceInterval: 0.56,
                maturityDuration: 1.7,
                petioleLengthScale: 0.58,
                pitchRangeDegrees: [38, 64],
                sizeRange: [0.7, 1.08],
            },
            phenology: {
                emergenceStart: 0.4,
                maturityGeneration: 10,
            },
            reproduction: {
                flowerStart: 5.75,
                flowersPerSite: 1,
                form: 'star',
                fruitStart: 7.75,
                produceCount: 5,
                site: 'axillary',
                siteCount: 2,
            },
            special: { tendrilCount: 10 },
            variability: 0.14,
        }),
        vegetable: {
            enabled: true,
            type: 'cucumber',
            baseSize: 0.3,
        },
    }),
    zucchini: createPlant('zucchini', {
        ...cucurbitAppearance,
        name: 'Tikvice',
        height: 0.68,
        development: createDevelopmentProgram('upright', {
            axes: {
                axisCount: 3,
                branchCount: 1,
                branchLengthScale: 0.3,
                branchNodeCount: 2,
                branchPitchDegrees: 30,
                branchingPattern: 'multi-stem',
                habit: 'basal',
                nodeCount: 5,
                pitchDegrees: 18,
                spread: 0.62,
            },
            foliage: {
                arrangement: 'rosette',
                count: 14,
                emergenceInterval: 0.5,
                maturityDuration: 1.9,
                petioleLengthScale: 0.62,
                pitchRangeDegrees: [32, 62],
                sizeRange: [0.72, 1.1],
            },
            phenology: {
                emergenceStart: 0.35,
                maturityGeneration: 10,
            },
            reproduction: {
                flowerStart: 5.75,
                flowersPerSite: 1,
                form: 'star',
                fruitStart: 7.75,
                produceCount: 4,
                site: 'axillary',
                siteCount: 2,
            },
            variability: 0.11,
        }),
        leaf: {
            ...cucurbitAppearance.leaf,
            size: 0.42,
            color: '#608a35',
        },
        vegetable: {
            enabled: true,
            type: 'zucchini',
            baseSize: 0.35,
        },
    }),
    pumpkin: createPlant('pumpkin', {
        ...cucurbitAppearance,
        name: 'Tikva',
        height: 0.56,
        development: createDevelopmentProgram('vine', {
            axes: {
                branchCount: 5,
                branchLengthScale: 0.46,
                branchNodeCount: 3,
                branchPitchDegrees: 16,
                habit: 'prostrate',
                nodeCount: 12,
                pitchDegrees: 4,
                spread: 0.68,
            },
            foliage: {
                count: 15,
                emergenceInterval: 0.52,
                maturityDuration: 1.8,
                petioleLengthScale: 0.62,
                pitchRangeDegrees: [36, 60],
                sizeRange: [0.7, 1.1],
            },
            phenology: {
                emergenceStart: 0.4,
                maturityGeneration: 10.5,
            },
            reproduction: {
                flowerStart: 6,
                flowersPerSite: 1,
                form: 'star',
                fruitStart: 8,
                produceCount: 2,
                site: 'axillary',
                siteCount: 2,
            },
            special: { tendrilCount: 12 },
            variability: 0.16,
        }),
        leaf: {
            ...cucurbitAppearance.leaf,
            size: 0.44,
            color: '#648930',
        },
        vegetable: {
            enabled: true,
            type: 'pumpkin',
            baseSize: 0.44,
        },
    }),
    melon: createPlant('melon', {
        ...cucurbitAppearance,
        name: 'Dinja',
        height: 0.58,
        development: createDevelopmentProgram('vine', {
            axes: {
                branchCount: 4,
                branchLengthScale: 0.42,
                branchNodeCount: 2,
                branchPitchDegrees: 18,
                habit: 'prostrate',
                nodeCount: 11,
                pitchDegrees: 4,
                spread: 0.62,
            },
            foliage: {
                count: 13,
                emergenceInterval: 0.55,
                maturityDuration: 1.75,
                petioleLengthScale: 0.56,
                pitchRangeDegrees: [36, 60],
                sizeRange: [0.7, 1.06],
            },
            phenology: {
                emergenceStart: 0.4,
                maturityGeneration: 10.25,
            },
            reproduction: {
                flowerStart: 6,
                flowersPerSite: 1,
                form: 'star',
                fruitStart: 8,
                produceCount: 3,
                site: 'axillary',
                siteCount: 2,
            },
            special: { tendrilCount: 10 },
            variability: 0.14,
        }),
        leaf: {
            ...cucurbitAppearance.leaf,
            size: 0.4,
            color: '#6c933e',
        },
        vegetable: {
            enabled: true,
            type: 'melon',
            baseSize: 0.4,
        },
    }),
};
