import type { PlantDefinition } from '../plant-definition-types';
import { createDevelopmentProgram, createPlant } from './helpers';

const fruitingAppearance = {
    height: 1.02,
    stem: {
        color: '#5f7631',
        radius: 0.046,
        radiusDecay: 0.55,
        minRadius: 0.005,
    },
    leaf: {
        color: '#486724',
        size: 0.24,
        type: 'oval',
    },
    flower: {
        enabled: true,
        color: '#f7ea72',
        size: 0.075,
    },
} satisfies Pick<PlantDefinition, 'flower' | 'height' | 'leaf' | 'stem'>;

export const fruitingPlants = {
    tomato: createPlant('tomato', {
        ...fruitingAppearance,
        name: 'Rajčica',
        height: 1.08,
        development: createDevelopmentProgram('upright', {
            axes: {
                branchCount: 4,
                branchLengthScale: 0.5,
                branchNodeCount: 3,
                branchPitchDegrees: 42,
                branchingPattern: 'sympodial',
                nodeCount: 10,
                spread: 0.24,
            },
            foliage: {
                count: 13,
                emergenceInterval: 0.6,
                maturityDuration: 1.7,
                petioleLengthScale: 0.55,
                pitchRangeDegrees: [38, 66],
                sizeRange: [0.7, 1.05],
            },
            phenology: {
                emergenceStart: 0.45,
                maturityGeneration: 10.5,
            },
            reproduction: {
                flowerStart: 6,
                flowersPerSite: 1,
                form: 'star',
                fruitStart: 8,
                produceCount: 10,
                site: 'truss',
                siteCount: 2,
            },
            variability: 0.12,
        }),
        stem: {
            ...fruitingAppearance.stem,
            color: '#5a6e2a',
        },
        leaf: {
            ...fruitingAppearance.leaf,
            color: '#3d5a1a',
            type: 'compound',
            size: 0.23,
        },
        flower: {
            ...fruitingAppearance.flower,
            color: '#ffff00',
        },
        vegetable: {
            enabled: true,
            type: 'tomato',
            baseSize: 0.16,
        },
    }),
    bellpepper: createPlant('bellpepper', {
        ...fruitingAppearance,
        name: 'Paprika',
        height: 0.86,
        development: createDevelopmentProgram('upright', {
            axes: {
                branchCount: 4,
                branchLengthScale: 0.42,
                branchNodeCount: 2,
                branchPitchDegrees: 38,
                branchingPattern: 'forked',
                nodeCount: 7,
                spread: 0.3,
            },
            foliage: {
                count: 12,
                emergenceInterval: 0.65,
                maturityDuration: 1.75,
                petioleLengthScale: 0.42,
                pitchRangeDegrees: [30, 54],
                sizeRange: [0.72, 1.04],
            },
            phenology: {
                emergenceStart: 0.45,
                maturityGeneration: 10.5,
            },
            reproduction: {
                flowerStart: 6.25,
                flowersPerSite: 1,
                form: 'star',
                fruitStart: 8.25,
                produceCount: 4,
                site: 'axillary',
                siteCount: 1,
            },
            variability: 0.07,
        }),
        stem: {
            ...fruitingAppearance.stem,
            color: '#4f7a28',
            radius: 0.056,
            radiusDecay: 0.6,
            minRadius: 0.006,
        },
        leaf: {
            ...fruitingAppearance.leaf,
            color: '#3a591f',
            size: 0.22,
        },
        flower: {
            ...fruitingAppearance.flower,
            color: '#ffffff',
            size: 0.065,
        },
        vegetable: {
            enabled: true,
            type: 'bellpepper',
            baseSize: 0.21,
        },
    }),
    eggplant: createPlant('eggplant', {
        ...fruitingAppearance,
        name: 'Patlidžan',
        height: 0.94,
        development: createDevelopmentProgram('upright', {
            axes: {
                branchCount: 4,
                branchLengthScale: 0.46,
                branchNodeCount: 2,
                branchPitchDegrees: 36,
                branchingPattern: 'forked',
                nodeCount: 7,
                spread: 0.3,
            },
            foliage: {
                count: 12,
                emergenceInterval: 0.65,
                maturityDuration: 1.85,
                petioleLengthScale: 0.46,
                pitchRangeDegrees: [32, 56],
                sizeRange: [0.74, 1.08],
            },
            phenology: {
                emergenceStart: 0.45,
                maturityGeneration: 10.75,
            },
            reproduction: {
                flowerStart: 6.25,
                flowersPerSite: 1,
                form: 'star',
                fruitStart: 8.25,
                produceCount: 3,
                site: 'axillary',
                siteCount: 1,
            },
            variability: 0.1,
        }),
        stem: {
            ...fruitingAppearance.stem,
            color: '#62783b',
            radius: 0.05,
        },
        leaf: {
            ...fruitingAppearance.leaf,
            color: '#4f6b33',
            size: 0.27,
        },
        flower: {
            ...fruitingAppearance.flower,
            color: '#d8b6ff',
            size: 0.07,
        },
        vegetable: {
            enabled: true,
            type: 'eggplant',
            baseSize: 0.22,
        },
    }),
    artichoke: createPlant('artichoke', {
        ...fruitingAppearance,
        name: 'Artičoka',
        height: 0.82,
        development: createDevelopmentProgram('rosette', {
            axes: { spread: 1.08 },
            foliage: {
                count: 16,
                emergenceInterval: 0.5,
                maturityDuration: 2.2,
                petioleLengthScale: 0.2,
                pitchRangeDegrees: [30, 66],
                sizeRange: [0.72, 1.1],
            },
            phenology: {
                emergenceStart: 0.3,
                maturityGeneration: 10.5,
            },
            reproduction: {
                flowerStart: 7,
                flowersPerSite: 1,
                form: 'pom-pom',
                fruitStart: 8.25,
                produceCount: 3,
                site: 'terminal',
                siteCount: 3,
            },
            variability: 0.09,
        }),
        stem: {
            ...fruitingAppearance.stem,
            color: '#6e8450',
            radius: 0.06,
        },
        leaf: {
            ...fruitingAppearance.leaf,
            color: '#718c56',
            size: 0.34,
            type: 'serrated',
        },
        flower: {
            ...fruitingAppearance.flower,
            enabled: false,
            size: 0,
        },
        vegetable: {
            enabled: true,
            type: 'artichoke',
            baseSize: 0.28,
        },
    }),
    okra: createPlant('okra', {
        ...fruitingAppearance,
        name: 'Bamija',
        height: 0.96,
        development: createDevelopmentProgram('upright', {
            axes: {
                branchCount: 2,
                branchLengthScale: 0.38,
                branchNodeCount: 2,
                branchPitchDegrees: 38,
                nodeCount: 9,
                spread: 0.2,
            },
            foliage: {
                count: 11,
                emergenceInterval: 0.66,
                maturityDuration: 1.75,
                petioleLengthScale: 0.54,
                pitchRangeDegrees: [34, 60],
                sizeRange: [0.72, 1.08],
            },
            phenology: {
                emergenceStart: 0.45,
                maturityGeneration: 10.5,
            },
            reproduction: {
                flowerStart: 6,
                flowersPerSite: 1,
                form: 'star',
                fruitStart: 8,
                produceCount: 6,
                site: 'axillary',
                siteCount: 1,
            },
            variability: 0.11,
        }),
        stem: {
            ...fruitingAppearance.stem,
            color: '#56793d',
        },
        leaf: {
            ...fruitingAppearance.leaf,
            color: '#4f7d2f',
            size: 0.25,
            type: 'palmate',
        },
        flower: {
            ...fruitingAppearance.flower,
            color: '#fff0d7',
            size: 0.08,
        },
        vegetable: {
            enabled: true,
            type: 'okra',
            baseSize: 0.18,
        },
    }),
};
