import type { PlantDefinition } from '../plant-definition-types';
import { createDevelopmentProgram, createPlant } from './helpers';

const herbVegetable: PlantDefinition['vegetable'] = {
    enabled: false,
    type: 'tomato',
    baseSize: 0.12,
};

export const herbPlants = {
    basil: createPlant('basil', {
        name: 'Bosiljak',
        development: createDevelopmentProgram('upright', {
            axes: {
                axisCount: 3,
                branchCount: 6,
                branchLengthScale: 0.42,
                branchNodeCount: 3,
                branchingPattern: 'opposite',
                nodeCount: 8,
                spread: 0.26,
            },
            foliage: {
                arrangement: 'opposite',
                count: 32,
                emergenceInterval: 0.27,
                petioleLengthScale: 0.32,
                pitchRangeDegrees: [34, 60],
                sizeRange: [0.7, 1.08],
            },
            phenology: { maturityGeneration: 10 },
            reproduction: {
                flowerStart: 8,
                flowersPerSite: 1,
                form: 'spike',
                site: 'spike',
                siteCount: 4,
            },
            variability: 0.12,
        }),
        height: 0.56,
        stem: {
            color: '#688741',
            radius: 0.017,
            radiusDecay: 0.55,
            minRadius: 0.002,
        },
        leaf: {
            color: '#72a13d',
            size: 0.18,
            type: 'oval',
        },
        flower: {
            enabled: true,
            color: '#f6f2df',
            size: 0.05,
        },
        vegetable: herbVegetable,
    }),
    dill: createPlant('dill', {
        name: 'Kopar',
        development: createDevelopmentProgram('upright', {
            axes: {
                axisCount: 2,
                branchCount: 5,
                branchLengthScale: 0.5,
                branchNodeCount: 3,
                branchPitchDegrees: 38,
                branchingPattern: 'alternate',
                nodeCount: 10,
                spread: 0.2,
            },
            foliage: {
                arrangement: 'alternate',
                count: 18,
                emergenceInterval: 0.46,
                petioleLengthScale: 0.58,
                pitchRangeDegrees: [38, 64],
                sizeRange: [0.7, 1.08],
            },
            phenology: { maturityGeneration: 11 },
            reproduction: {
                flowerStart: 9,
                flowersPerSite: 1,
                form: 'umbel',
                site: 'umbel',
                siteCount: 5,
            },
            variability: 0.08,
        }),
        height: 0.82,
        stem: {
            color: '#769b49',
            radius: 0.017,
            radiusDecay: 0.55,
            minRadius: 0.002,
        },
        leaf: {
            color: '#89b658',
            size: 0.12,
            type: 'feathery',
        },
        flower: {
            enabled: true,
            color: '#ecd75b',
            size: 0.05,
        },
        vegetable: herbVegetable,
    }),
    coriander: createPlant('coriander', {
        name: 'Korijandar',
        development: createDevelopmentProgram('upright', {
            axes: {
                axisCount: 3,
                branchCount: 4,
                branchLengthScale: 0.46,
                branchNodeCount: 2,
                branchingPattern: 'forked',
                nodeCount: 7,
                spread: 0.28,
            },
            foliage: {
                arrangement: 'alternate',
                count: 18,
                emergenceInterval: 0.44,
                petioleLengthScale: 0.48,
                pitchRangeDegrees: [36, 64],
                sizeRange: [0.72, 1.06],
            },
            phenology: { maturityGeneration: 10 },
            reproduction: {
                flowerStart: 8,
                flowersPerSite: 1,
                form: 'umbel',
                site: 'umbel',
                siteCount: 4,
            },
        }),
        height: 0.58,
        stem: {
            color: '#688741',
            radius: 0.017,
            radiusDecay: 0.55,
            minRadius: 0.002,
        },
        leaf: {
            color: '#5f8a2f',
            size: 0.15,
            type: 'pinnate',
        },
        flower: {
            enabled: true,
            color: '#ffffff',
            size: 0.05,
        },
        vegetable: herbVegetable,
    }),
    lovage: createPlant('lovage', {
        name: 'Ljupčac',
        development: createDevelopmentProgram('upright', {
            axes: {
                axisCount: 3,
                branchCount: 4,
                branchLengthScale: 0.5,
                branchNodeCount: 2,
                branchingPattern: 'multi-stem',
                nodeCount: 8,
                spread: 0.3,
            },
            foliage: {
                arrangement: 'alternate',
                count: 16,
                emergenceInterval: 0.5,
                petioleLengthScale: 0.6,
                pitchRangeDegrees: [38, 68],
                sizeRange: [0.72, 1.08],
            },
            phenology: { maturityGeneration: 10.5 },
        }),
        height: 0.92,
        stem: {
            color: '#688741',
            radius: 0.019,
            radiusDecay: 0.55,
            minRadius: 0.002,
        },
        leaf: {
            color: '#5f8a2f',
            size: 0.17,
            type: 'pinnate',
        },
        flower: {
            enabled: false,
            color: '#f2ecd1',
            size: 0,
        },
        vegetable: herbVegetable,
    }),
    oregano: createPlant('oregano', {
        name: 'Origano',
        development: createDevelopmentProgram('shrub', {
            axes: {
                axisCount: 5,
                branchCount: 7,
                branchLengthScale: 0.46,
                branchNodeCount: 3,
                branchingPattern: 'opposite',
                habit: 'upright',
                nodeCount: 7,
                spread: 0.42,
            },
            foliage: {
                arrangement: 'opposite',
                count: 40,
                emergenceInterval: 0.21,
                petioleLengthScale: 0.2,
                pitchRangeDegrees: [34, 62],
                sizeRange: [0.68, 1.04],
            },
            phenology: { maturityGeneration: 10 },
            reproduction: {
                flowerStart: 8,
                flowersPerSite: 1,
                form: 'cluster',
                site: 'terminal',
                siteCount: 6,
            },
            variability: 0.13,
        }),
        height: 0.42,
        stem: {
            color: '#688741',
            radius: 0.017,
            radiusDecay: 0.55,
            minRadius: 0.002,
        },
        leaf: {
            color: '#5f8a2f',
            size: 0.1,
            type: 'oval',
        },
        flower: {
            enabled: true,
            color: '#c6a2da',
            size: 0.05,
        },
        vegetable: herbVegetable,
    }),
    parsley: createPlant('parsley', {
        name: 'Peršin',
        development: createDevelopmentProgram('upright', {
            axes: {
                axisCount: 4,
                branchCount: 1,
                branchLengthScale: 0.28,
                branchNodeCount: 1,
                branchPitchDegrees: 54,
                branchingPattern: 'multi-stem',
                habit: 'basal',
                nodeCount: 5,
                pitchDegrees: 10,
                spread: 0.46,
            },
            foliage: {
                arrangement: 'rosette',
                count: 18,
                emergenceInterval: 0.43,
                petioleLengthScale: 0.7,
                pitchRangeDegrees: [42, 72],
                sizeRange: [0.7, 1.08],
            },
            phenology: { maturityGeneration: 9.5 },
        }),
        height: 0.5,
        stem: {
            color: '#688741',
            radius: 0.017,
            radiusDecay: 0.55,
            minRadius: 0.002,
        },
        leaf: {
            color: '#5f8a2f',
            size: 0.16,
            type: 'pinnate',
        },
        flower: {
            enabled: false,
            color: '#f2ecd1',
            size: 0,
        },
        vegetable: herbVegetable,
    }),
    thyme: createPlant('thyme', {
        name: 'Timijan',
        development: createDevelopmentProgram('shrub', {
            axes: {
                axisCount: 6,
                branchCount: 8,
                branchLengthScale: 0.4,
                branchNodeCount: 3,
                branchPitchDegrees: 34,
                branchingPattern: 'opposite',
                habit: 'upright',
                nodeCount: 7,
                spread: 0.48,
            },
            foliage: {
                arrangement: 'opposite',
                count: 44,
                emergenceInterval: 0.19,
                petioleLengthScale: 0.12,
                pitchRangeDegrees: [30, 58],
                sizeRange: [0.66, 1.02],
            },
            phenology: { maturityGeneration: 10.5 },
            reproduction: {
                flowerStart: 9,
                flowersPerSite: 1,
                form: 'cluster',
                site: 'terminal',
                siteCount: 8,
            },
            variability: 0.14,
        }),
        height: 0.26,
        stem: {
            color: '#688741',
            radius: 0.012,
            radiusDecay: 0.55,
            minRadius: 0.002,
        },
        leaf: {
            color: '#5f8a2f',
            size: 0.08,
            type: 'lanceolate',
        },
        flower: {
            enabled: true,
            color: '#b997de',
            size: 0.04,
        },
        vegetable: herbVegetable,
    }),
};
