import type { PlantDefinition } from '../plant-definition-types';
import { createDevelopmentProgram, createPlant } from './helpers';

const legumeAppearance = {
    height: 0.88,
    stem: {
        color: '#5d7e36',
        radius: 0.024,
        radiusDecay: 0.5,
        minRadius: 0.003,
    },
    leaf: {
        color: '#5e8a30',
        size: 0.18,
        type: 'compound',
    },
    flower: {
        enabled: true,
        color: '#ffffff',
        size: 0.06,
    },
} satisfies Pick<PlantDefinition, 'flower' | 'height' | 'leaf' | 'stem'>;

export const legumePlants = {
    broadbean: createPlant('broadbean', {
        ...legumeAppearance,
        name: 'Bob',
        height: 0.9,
        development: createDevelopmentProgram('upright', {
            axes: {
                axisCount: 2,
                branchCount: 2,
                branchLengthScale: 0.34,
                branchNodeCount: 2,
                branchPitchDegrees: 38,
                branchingPattern: 'multi-stem',
                nodeCount: 8,
                spread: 0.22,
            },
            foliage: {
                arrangement: 'opposite',
                count: 14,
                emergenceInterval: 0.58,
                maturityDuration: 1.65,
                petioleLengthScale: 0.32,
                pitchRangeDegrees: [34, 58],
                sizeRange: [0.72, 1.05],
            },
            phenology: {
                emergenceStart: 0.4,
                maturityGeneration: 10,
            },
            reproduction: {
                flowerStart: 6,
                flowersPerSite: 1,
                form: 'pea',
                fruitStart: 8,
                produceCount: 6,
                site: 'axillary',
                siteCount: 1,
            },
            variability: 0.1,
        }),
        leaf: {
            ...legumeAppearance.leaf,
            size: 0.22,
            type: 'oval',
        },
        flower: {
            ...legumeAppearance.flower,
            color: '#f7f7f7',
        },
        vegetable: {
            enabled: true,
            type: 'beanpod',
            baseSize: 0.25,
        },
    }),
    bean: createPlant('bean', {
        ...legumeAppearance,
        name: 'Grah',
        height: 0.92,
        development: createDevelopmentProgram('upright', {
            axes: {
                branchCount: 3,
                branchLengthScale: 0.4,
                branchNodeCount: 2,
                branchPitchDegrees: 40,
                branchingPattern: 'opposite',
                nodeCount: 8,
                spread: 0.24,
            },
            foliage: {
                arrangement: 'opposite',
                count: 14,
                emergenceInterval: 0.58,
                maturityDuration: 1.65,
                petioleLengthScale: 0.4,
                pitchRangeDegrees: [34, 60],
                sizeRange: [0.7, 1.06],
            },
            phenology: {
                emergenceStart: 0.4,
                maturityGeneration: 10,
            },
            reproduction: {
                flowerStart: 6,
                flowersPerSite: 1,
                form: 'pea',
                fruitStart: 8,
                produceCount: 7,
                site: 'axillary',
                siteCount: 2,
            },
            variability: 0.12,
        }),
        vegetable: {
            enabled: true,
            type: 'beanpod',
            baseSize: 0.22,
        },
    }),
    pea: createPlant('pea', {
        ...legumeAppearance,
        name: 'Grašak',
        height: 0.8,
        development: createDevelopmentProgram('vine', {
            axes: {
                branchCount: 3,
                branchLengthScale: 0.38,
                branchNodeCount: 2,
                branchPitchDegrees: 22,
                habit: 'climbing',
                nodeCount: 10,
                pitchDegrees: 66,
                spread: 0.28,
            },
            foliage: {
                arrangement: 'opposite',
                count: 15,
                emergenceInterval: 0.52,
                maturityDuration: 1.6,
                petioleLengthScale: 0.36,
                pitchRangeDegrees: [34, 58],
                sizeRange: [0.7, 1.05],
            },
            phenology: {
                emergenceStart: 0.4,
                maturityGeneration: 9.75,
            },
            reproduction: {
                flowerStart: 5.5,
                flowersPerSite: 1,
                form: 'pea',
                fruitStart: 7.5,
                produceCount: 8,
                site: 'axillary',
                siteCount: 2,
            },
            special: { tendrilCount: 12 },
            variability: 0.14,
        }),
        leaf: {
            ...legumeAppearance.leaf,
            size: 0.16,
        },
        flower: {
            ...legumeAppearance.flower,
            color: '#f2edf7',
        },
        vegetable: {
            enabled: true,
            type: 'peapod',
            baseSize: 0.19,
        },
    }),
    greenbean: createPlant('greenbean', {
        ...legumeAppearance,
        name: 'Mahuna',
        height: 0.84,
        development: createDevelopmentProgram('vine', {
            axes: {
                branchCount: 3,
                branchLengthScale: 0.4,
                branchNodeCount: 2,
                branchPitchDegrees: 24,
                habit: 'climbing',
                nodeCount: 11,
                pitchDegrees: 68,
                spread: 0.26,
            },
            foliage: {
                count: 14,
                emergenceInterval: 0.54,
                maturityDuration: 1.6,
                petioleLengthScale: 0.4,
                pitchRangeDegrees: [34, 58],
                sizeRange: [0.7, 1.06],
            },
            phenology: {
                emergenceStart: 0.4,
                maturityGeneration: 10,
            },
            reproduction: {
                flowerStart: 5.75,
                flowersPerSite: 1,
                form: 'pea',
                fruitStart: 7.75,
                produceCount: 9,
                site: 'axillary',
                siteCount: 2,
            },
            special: { tendrilCount: 0 },
            variability: 0.14,
        }),
        vegetable: {
            enabled: true,
            type: 'beanpod',
            baseSize: 0.2,
        },
    }),
};
