import { BackpackIcon } from '@gredice/ui/BackpackIcon';
import {
    GameBackpackIcon,
    GameCameraIcon,
    GameHistoryIcon,
    GameInformationIcon,
    GameJournalIcon,
    GameMailboxIcon,
    GameRaisedBedSimpleIcon,
    GameSeedlingIcon,
    GameSeedPacketIcon,
    GameShovelIcon,
    GameTasksIcon,
    GameToolsIcon,
} from '@gredice/ui/GameIcons';
import {
    Book,
    Camera,
    Hammer,
    History,
    Inbox,
    Info,
    ListTodo,
    Sprout,
} from '@gredice/ui/icons';
import { PlantingSeedIcon } from '@gredice/ui/PlantingSeedIcon';
import { RaisedBedSimpleIcon } from '@gredice/ui/RaisedBedSimpleIcon';
import { ShovelIcon } from '@gredice/ui/ShovelIcon';

export const gameIconComparisons = [
    {
        name: 'Backpack',
        before: BackpackIcon,
        after: GameBackpackIcon,
        usage: 'Inventory, operations, plant choices and shopping cart',
        legacyName: 'BackpackIcon',
        componentName: 'GameBackpackIcon',
        sources: [
            'packages/ui/src/GameIcons/GameBackpackIcon.tsx',
            'packages/game/src/hud/InventoryHud.tsx',
            'packages/game/src/hud/raisedBed/PlantsSortList.tsx',
            'packages/game/src/hud/raisedBed/shared/OperationsListItem.tsx',
            'packages/game/src/hud/components/shopping-cart/ShoppingCartItem.tsx',
        ],
    },
    {
        name: 'Mailbox',
        before: Inbox,
        after: GameMailboxIcon,
        usage: 'Notifications',
        legacyName: 'Inbox',
        componentName: 'GameMailboxIcon',
        sources: [
            'packages/ui/src/GameIcons/GameMailboxIcon.tsx',
            'packages/game/src/hud/AccountHud.tsx',
            'packages/game/src/hud/GardenOperationsHud.tsx',
        ],
    },
    {
        name: 'Task board',
        before: ListTodo,
        after: GameTasksIcon,
        usage: 'Garden operations',
        legacyName: 'ListTodo',
        componentName: 'GameTasksIcon',
        sources: [
            'packages/ui/src/GameIcons/GameTasksIcon.tsx',
            'packages/game/src/hud/GardenOperationsHud.tsx',
            'packages/game/src/shared-ui/sunflowers/SunflowersList.tsx',
        ],
    },
    {
        name: 'Seed packet',
        before: PlantingSeedIcon,
        after: GameSeedPacketIcon,
        usage: 'Sowing and empty fields',
        legacyName: 'PlantingSeedIcon',
        componentName: 'GameSeedPacketIcon',
        sources: [
            'packages/ui/src/GameIcons/GameSeedPacketIcon.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedField.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedFieldItem.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedFieldItemEmpty.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedPlantPicker.tsx',
        ],
    },
    {
        name: 'Seedling',
        before: Sprout,
        after: GameSeedlingIcon,
        usage: 'Plants, greenhouse and recommendations',
        legacyName: 'Sprout',
        componentName: 'GameSeedlingIcon',
        sources: [
            'packages/ui/src/GameIcons/GameSeedlingIcon.tsx',
            'packages/game/src/generators/plant/editor/components/PlantControl.tsx',
            'packages/game/src/hud/AccountHud.tsx',
            'packages/game/src/hud/DetailedRaisedBedInspectionModal.tsx',
            'packages/game/src/hud/GardenTargetHighlightHud.tsx',
            'packages/game/src/hud/RaisedBedOnboardingModal.tsx',
            'packages/game/src/hud/SuncokretRecommendationChips.tsx',
            'packages/game/src/hud/components/shopping-cart/GreenhouseSowingToggle.tsx',
            'packages/game/src/hud/components/shopping-cart/ShoppingCartItem.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedAdvancedSowingPlantingDetails.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedFieldItemPlanted.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedPlantPicker.tsx',
            'packages/game/src/viewers/OutletGardenBrowserViewer.tsx',
            'packages/game/src/viewers/OutletGardenCommerce.tsx',
            'packages/game/src/viewers/OutletGardenOfferBrowser.tsx',
            'packages/game/src/viewers/OutletGardenProductSigns.tsx',
            'packages/game/src/viewers/OutletGardenViewer.tsx',
            'packages/game/src/viewers/PublicGardenRaisedBedDetails.tsx',
        ],
    },
    {
        name: 'Raised bed',
        before: RaisedBedSimpleIcon,
        after: GameRaisedBedSimpleIcon,
        usage: 'Bed selection and context',
        legacyName: 'RaisedBedSimpleIcon',
        componentName: 'GameRaisedBedSimpleIcon',
        sources: [
            'packages/ui/src/GameIcons/GameRaisedBedSimpleIcon.tsx',
            'packages/game/src/viewers/PublicGardenRaisedBedDetails.tsx',
            'packages/game/src/viewers/PublicGardenRaisedBedPicker.tsx',
            'packages/game/src/hud/DetailedRaisedBedInspectionModal.tsx',
            'packages/game/src/hud/GardenOperationsHud.tsx',
            'packages/game/src/hud/NotificationList.tsx',
            'packages/game/src/hud/RaisedBedFieldHud.tsx',
            'packages/game/src/hud/components/shopping-cart/ShoppingCartItem.tsx',
            'packages/game/src/shared-ui/delivery/DeliveryRequestRow.tsx',
        ],
    },
    {
        name: 'Garden tools',
        before: Hammer,
        after: GameToolsIcon,
        usage: 'Gardening actions',
        legacyName: 'Hammer',
        componentName: 'GameToolsIcon',
        sources: [
            'packages/ui/src/GameIcons/GameToolsIcon.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedDetailsTabsList.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedFieldItemPlanted.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedFieldOperationsModal.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedInfo.tsx',
            'packages/game/src/hud/raisedBed/RecommendationsCard.tsx',
        ],
    },
    {
        name: 'Shovel',
        before: ShovelIcon,
        after: GameShovelIcon,
        usage: 'Lifecycle operations',
        legacyName: 'ShovelIcon',
        componentName: 'GameShovelIcon',
        sources: [
            'packages/ui/src/GameIcons/GameShovelIcon.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedFieldLifecycleTab.tsx',
        ],
    },
    {
        name: 'Journal',
        before: Book,
        after: GameJournalIcon,
        usage: 'Raised-bed diary',
        legacyName: 'Book',
        componentName: 'GameJournalIcon',
        sources: [
            'packages/ui/src/GameIcons/GameJournalIcon.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedDetailsTabsList.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedFieldItemPlanted.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedInfo.tsx',
        ],
    },
    {
        name: 'Information',
        before: Info,
        after: GameInformationIcon,
        usage: 'Bed information beside journal and actions',
        legacyName: 'Info',
        componentName: 'GameInformationIcon',
        sources: [
            'packages/ui/src/GameIcons/GameInformationIcon.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedDetailsTabsList.tsx',
        ],
    },
    {
        name: 'Camera',
        before: Camera,
        after: GameCameraIcon,
        usage: 'Bed and plant photos',
        legacyName: 'Camera',
        componentName: 'GameCameraIcon',
        sources: [
            'packages/ui/src/GameIcons/GameCameraIcon.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedPhotosModal.tsx',
        ],
    },
    {
        name: 'History',
        before: History,
        after: GameHistoryIcon,
        usage: 'Previous plants and garden actions',
        legacyName: 'History',
        componentName: 'GameHistoryIcon',
        sources: [
            'packages/ui/src/GameIcons/GameHistoryIcon.tsx',
            'packages/game/src/hud/GardenOperationsHud.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedField.tsx',
            'packages/game/src/hud/raisedBed/RaisedBedFieldItemPlanted.tsx',
        ],
    },
];
