import { KnownPages } from '../../../src/KnownPages';

export const adminPages = {
    Dashboard: { href: KnownPages.Dashboard, label: 'Početna' },
    Directories: { href: KnownPages.Directories, label: 'Zapisi' },
    DirectoriesActivity: {
        href: KnownPages.DirectoriesActivity,
        label: 'Aktivnosti',
    },
    CommunityEdits: {
        href: KnownPages.CommunityEdits,
        label: 'Prijedlozi zajednice',
    },
    CmsPages: { href: KnownPages.CmsPages, label: 'Stranice' },
    Accounts: { href: KnownPages.Accounts, label: 'Korisnički računi' },
    Achievements: { href: KnownPages.Achievements, label: 'Postignuća' },
    ShoppingCarts: { href: KnownPages.ShoppingCarts, label: 'Košarice' },
    Invoices: { href: KnownPages.Invoices, label: 'Ponude' },
    Transactions: { href: KnownPages.Transactions, label: 'Transakcije' },
    Sunflowers: { href: KnownPages.Sunflowers, label: 'Suncokreti' },
    Receipts: { href: KnownPages.Receipts, label: 'Fiskalni računi' },
    Users: { href: KnownPages.Users, label: 'Korisnici' },
    Farms: { href: KnownPages.Farms, label: 'Farme' },
    Weather: { href: KnownPages.Weather, label: 'Vrijeme' },
    Gardens: { href: KnownPages.Gardens, label: 'Vrtovi' },
    RaisedBeds: { href: KnownPages.RaisedBeds, label: 'Gredice' },
    HarvestTraces: { href: KnownPages.HarvestTraces, label: 'QR tragovi' },
    Operations: { href: KnownPages.Operations, label: 'Radnje' },
    FarmerPayouts: { href: KnownPages.FarmerPayouts, label: 'Isplate farmera' },
    FarmerPrices: { href: KnownPages.FarmerPrices, label: 'Cijene radnji' },
    Inventory: { href: KnownPages.Inventory, label: 'Zalihe' },
    Occasions: { href: KnownPages.Occasions, label: 'Prigode' },
    Approvals: { href: KnownPages.Approvals, label: 'Odobrenja' },
    Automations: { href: KnownPages.Automations, label: 'Automatizacije' },
    Schedule: { href: KnownPages.Schedule, label: 'Raspored' },
    SowingStatistics: {
        href: KnownPages.SowingStatistics,
        label: 'Statistika sijanja',
    },
    DeliverySlots: {
        href: KnownPages.DeliverySlots,
        label: 'Dostava - Slotovi',
    },
    DeliveryRequests: {
        href: KnownPages.DeliveryRequests,
        label: 'Dostava - Zahtjevi',
    },
    CommunicationInbox: {
        href: KnownPages.CommunicationInbox,
        label: 'Sandučić',
    },
    CommunicationEmails: {
        href: KnownPages.CommunicationEmails,
        label: 'Poslani emailovi',
    },
    CommunicationSlack: { href: KnownPages.CommunicationSlack, label: 'Slack' },
    Notifications: { href: KnownPages.Notifications, label: 'Obavijesti' },
    Feedback: { href: KnownPages.Feedback, label: 'Povratne informacije' },
    Settings: { href: KnownPages.Settings, label: 'Postavke' },
    Sensors: { href: KnownPages.Sensors, label: 'Senzori' },
    Cache: { href: KnownPages.Cache, label: 'Cache' },
    AiAnalytics: { href: KnownPages.AiAnalytics, label: 'AI analitika' },
    SocialPublishing: {
        href: KnownPages.SocialPublishing,
        label: 'Društvene objave',
    },
} as const;

export const adminBreadcrumbPages = [
    adminPages.Dashboard,
    adminPages.Directories,
    adminPages.DirectoriesActivity,
    adminPages.CommunityEdits,
    adminPages.CmsPages,
    adminPages.Accounts,
    adminPages.Achievements,
    adminPages.ShoppingCarts,
    adminPages.Invoices,
    adminPages.Transactions,
    adminPages.Sunflowers,
    adminPages.Receipts,
    adminPages.Users,
    adminPages.Farms,
    adminPages.Weather,
    adminPages.Gardens,
    adminPages.RaisedBeds,
    adminPages.HarvestTraces,
    adminPages.Operations,
    adminPages.FarmerPayouts,
    adminPages.FarmerPrices,
    adminPages.Approvals,
    adminPages.Inventory,
    adminPages.Occasions,
    adminPages.Schedule,
    adminPages.SowingStatistics,
    adminPages.DeliverySlots,
    adminPages.DeliveryRequests,
    adminPages.CommunicationInbox,
    adminPages.CommunicationEmails,
    adminPages.CommunicationSlack,
    adminPages.Notifications,
    adminPages.Feedback,
    adminPages.Automations,
    adminPages.Sensors,
    adminPages.Cache,
    adminPages.AiAnalytics,
    adminPages.Settings,
    adminPages.SocialPublishing,
] as const;
