#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PACKAGE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$PACKAGE_ROOT/.env.test"

hash_value() {
    if command -v shasum >/dev/null 2>&1; then
        printf '%s' "$1" | shasum -a 1 | awk '{ print substr($1, 1, 12) }'
        return
    fi

    if command -v sha1sum >/dev/null 2>&1; then
        printf '%s' "$1" | sha1sum | awk '{ print substr($1, 1, 12) }'
        return
    fi

    printf '%s' "$1" | cksum | awk '{ print $1 }'
}

WORKTREE_ID="$(hash_value "$PACKAGE_ROOT")"
RUN_ID="${GREDICE_TEST_RUN_ID:-$(date +%s)-$$-$RANDOM}"
SAFE_RUN_ID="$(printf '%s' "$RUN_ID" | tr -c '[:alnum:]_.-' '-' | cut -c1-32)"
CONTAINER_NAME="gredice-storage-test-db-$WORKTREE_ID-$SAFE_RUN_ID"
STARTED=0
COMPLETED=0

cleanup_started_container() {
    if [[ "$STARTED" == "1" && "$COMPLETED" != "1" ]]; then
        docker stop "$CONTAINER_NAME" >/dev/null 2>&1 || true
    fi
}

trap cleanup_started_container EXIT

docker run --rm -d \
    --name "$CONTAINER_NAME" \
    --label "gredice.storage.test=true" \
    --label "gredice.storage.test.worktree=$WORKTREE_ID" \
    -e POSTGRES_PASSWORD=postgres \
    -e POSTGRES_USER=postgres \
    -e POSTGRES_DB=gredice_test \
    -p 127.0.0.1::5432 \
    postgres:16 >/dev/null
STARTED=1

TEST_DB_PORT="$(docker port "$CONTAINER_NAME" 5432/tcp | awk -F: 'NR == 1 { print $NF }')"
if [[ -z "$TEST_DB_PORT" ]]; then
    echo "Failed to resolve dynamic Postgres host port for $CONTAINER_NAME." >&2
    exit 1
fi

READY=0
for _ in {1..60}; do
    if docker exec "$CONTAINER_NAME" pg_isready -U postgres -d gredice_test >/dev/null 2>&1; then
        READY=1
        break
    fi
    sleep 1
done

if [[ "$READY" != "1" ]]; then
    echo "Timed out waiting for storage test database container: $CONTAINER_NAME" >&2
    docker logs --tail=50 "$CONTAINER_NAME" >&2 || true
    exit 1
fi

POSTGRES_URL="postgres://postgres:postgres@localhost:$TEST_DB_PORT/gredice_test"
{
    echo "# Generated by packages/storage/tests/startTestDb.sh"
    echo "POSTGRES_URL=$POSTGRES_URL"
    echo "TEST_ENV=1"
    echo "GREDICE_TEST_DB_CONTAINER=$CONTAINER_NAME"
} > "$ENV_FILE"

echo "Storage test database ready:"
echo "  container: $CONTAINER_NAME"
echo "  .env.test: $ENV_FILE"
echo "  POSTGRES_URL=$POSTGRES_URL"

COMPLETED=1
trap - EXIT
